### ISSUE TITLE
ReferenceField opposite Reference

### ISSUE THREAD

**Issue by sarkistlt** [marmelab/admin-on-rest#1006]
lets assume I have an user table 
```js
const user = {
id:
name:
etc.
}
```

and subscription table 

```js
const subscription = {
id:
user_id:
active:
etc.
}
```

what I need is in the user list show some props from subscription, something like:

```js
<ReferenceField source="id" on="user_id" reference="Subscription">
   <TextField source="active" />
</ReferenceField>```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
