### ISSUE TITLE
icons on custom menus

### ISSUE THREAD

**Issue by ryantaylor16** [marmelab/admin-on-rest#1007]
I have created a custom menu and the icons that I have specified in the Admin section no longer work, I would assume there is a way to configure the icons in the Menu.js but am unsure how to do that. Any help would be appreciated.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by handyccc** [comment]
@ryantaylor16 This may be a little late, but I had the same issue, found that you can set the icon in the custom menu like this:

```
import CommentIcon from 'material-ui/svg-icons/action/info-outline';
...
<MenuItemLink to="/comments" primaryText="Comments" onClick={onMenuTap} leftIcon={<CommentIcon /> />

```

**Comment by fzaninotto** [comment]
@handyccc Thanks for your answer! May I suggest you look for @ryantaylor16's question on StackOverflow, and copy your answer there? It will make you a StackOverflow hero and help developers in the future. Thanks in advance!
