### ISSUE TITLE
BC break resources state

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#1029]
The state of resources used to live in state.admin.resource, but have been moved to state.admin.resources. No problem there, that's good, but it's a BC break and the project should have been tagged accordingly (major version bump). I can't think of a clean way to make this BC now, but I want to have this issue for others encountering the same.

Maybe it's a good idea to kick in some semver?

**Comment by fzaninotto** [comment]
We try to use semver strictly, and to never break existing apps.

Since we've never documented the Redux store structure, it was not a public API, so I consider it's not a BC break to change it. We can't commit on internals - it would be a major brake for refactorings. 

But I understand that it may be unexpected for developers. I'm sorry if it broke yours, and we'll be more cautious in the future with such changes.

**Comment by RWOverdijk** [comment]
Thanks for your quick reply 👍  

From the docs:

> In fact, it has an internal instance pool (in state.admin[resource]) that is kept during navigation, and uses it to render the screen before the API calls are over - it’s called optimistic rendering.

It's there, that's why I use(d) it. But I understand your reasoning! In any case this ticket serves as a reference point to other developers. :) Happy coding 😄

**Comment by fzaninotto** [comment]
Damn, I wrote that doc, too! My bad, and apologies.

**Comment by RWOverdijk** [comment]
No problem, glad I could help.
