### ISSUE TITLE
How to handle GET_LIST using a preview and GET using the actual entity

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1043]
## Issue Type

- [x ] Features

## Description

When I get from my spring data rest api a single entity, I don't have any `id` field in my entity but a `self.href` url.

```jsx harmony
{
  "username" : "user2",
  "createdDate" : "2017-09-17T04:28:36.576Z",
  "lastModifiedDate" : "2017-09-17T04:35:49.449Z",
  "createdById" : null,
  "lastModifiedById" : 1,
  "active" : true,
  "enabled" : true,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/managers/2"
    },
    "manager" : {
      "href" : "http://localhost:8080/managers/2{?projection}",
      "templated" : true
    },
    "roleList" : {
      "href" : "http://localhost:8080/managers/2/roleList"
    }
  }
}
```

This is not true when I get the preview.

```jsx harmony
{
  "_embedded" : {
    "managers" : [ {
      "username" : "user2",
      "active" : true,
      "roleList" : [ ],
      "createdDate" : "2017-09-17T04:28:36.576Z",
      "id" : 2,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/managers/2"
        },
        "manager" : {
          "href" : "http://localhost:8080/managers/2{?projection}",
          "templated" : true
        },
        "roleList" : {
          "href" : "http://localhost:8080/managers/2/roleList"
        }
      }
    }, {
      "username" : "user1",
      "active" : true,
      "roleList" : [ {
        "createdDate" : "2017-09-17T04:28:36.322Z",
        "createdById" : null,
        "lastModifiedById" : null,
        "active" : true,
        "name" : "ADMIN"
      }, {
        "createdDate" : "2017-09-17T04:28:36.332Z",
        "createdById" : null,
        "lastModifiedById" : null,
        "active" : true,
        "name" : "USER"
      }, {
        "createdDate" : "2017-09-17T04:28:36.335Z",
        "createdById" : null,
        "lastModifiedById" : null,
        "active" : true,
        "name" : "CLIENT"
      } ],
      "createdDate" : "2017-09-17T04:28:36.463Z",
      "id" : 1,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/managers/1"
        },
        "manager" : {
          "href" : "http://localhost:8080/managers/1{?projection}",
          "templated" : true
        },
        "roleList" : {
          "href" : "http://localhost:8080/managers/1/roleList"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/managers{?projection}",
      "templated" : true
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/managers"
    },
    "search" : {
      "href" : "http://localhost:8080/managers/search"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 2,
    "totalPages" : 1,
    "number" : 0
  }
}
```

According the the spring-data team https://github.com/spring-projects/spring-hateoas/issues/66 and only them, the entity should never send it's `id` to the client as the entity `self` url is all the client need to manipulate the data.

This lead me to this thinking, how do we handle these url in AOR ?

# Versions

- AOR: 1.3.0
- Node/NPM: 8.4.0/5.4.2

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
