### ISSUE TITLE
Error on Creating custom ReferenceInput with separate component

### ISSUE THREAD

**Issue by taweesoft** [marmelab/admin-on-rest#1049]
I'm trying to creating my ReferenceInput which contains SelectInput inside of it.

The code below is works perfectly (Please focus at ReferenceInput)
<img width="767" alt="screen shot 2560-09-19 at 11 25 19" src="https://user-images.githubusercontent.com/8603253/30575888-02c3b9a8-9d2e-11e7-95dd-83f9faa8aaa5.png">

However, I would like to separate it into another component and pass data as props. I made it like this.
<img width="781" alt="screen shot 2560-09-19 at 11 25 44" src="https://user-images.githubusercontent.com/8603253/30575898-1bb9ce5c-9d2e-11e7-9276-ab1e3f232452.png">
<img width="821" alt="screen shot 2560-09-19 at 11 25 52" src="https://user-images.githubusercontent.com/8603253/30575900-1d69b672-9d2e-11e7-9c15-371538079a17.png">

When I run it, this error occurs
<img width="525" alt="screen shot 2560-09-19 at 11 28 10" src="https://user-images.githubusercontent.com/8603253/30575925-42bedc7c-9d2e-11e7-8d75-e6ae7ab4adc5.png">

in this file https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/src/mui/input/ReferenceInput.js#L243

What wrong did I do ?

Thanks

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
