### ISSUE TITLE
DeleteButton not working - aor-firebase-client

### ISSUE THREAD

**Issue by sidferreira** [marmelab/admin-on-rest#1060]
Guys, I'm the maintainer of `aor-firebase-client` and happens that the DELETE button stopped working. I'm trying to debug but I'm not having much progress on that.

Can you guys help me to dig into the issue?
At this moment, is you click delete it will just go to the URL 
`http://localhost:3000/#/${resource}/${id}/delete`

**Comment by fzaninotto** [comment]
The delete button leads to a page asking for confirmation, at the URL you pasted (http://localhost:3000/#/${resource}/${id}/delete):

![image](https://user-images.githubusercontent.com/99944/30644392-7f8a2e56-9e12-11e7-82a1-68daa8147444.png)

This is normal. To display this page, AOR calls the REST client with `GET_ONE`:

![image](https://user-images.githubusercontent.com/99944/30644475-cb8bd3a4-9e12-11e7-94e9-1786d2f9f59a.png)

Can you be more specific about what your issue is and what error you get? 

Also, as the DELETE button works with the provided REST clients, I'm closing this issue - there is no bug in AOR. But feel free to continue the discussion.

**Comment by sidferreira** [comment]
@fzaninotto Thanks! This feedback might be enough. Sorry for using an ISSUE, I had no better idea how to get a quick response. `Indeed there's no bug in AOR.`

**Comment by sidferreira** [comment]
@fzaninotto Does DELETE requires user to be authed?
I did another test now, and still not work.
![screenshot 2017-09-20 10 25 17](https://user-images.githubusercontent.com/143615/30674235-0d7d88e8-9e4f-11e7-9868-1bce4d37a230.png)

**Comment by fzaninotto** [comment]
Before the display of every page (the delete page including), aor makes a call to the `authClient` with the `AUTH_CHECK` verb. So if you have an `authClient`, yes, the Delete page requires authentication.

**Comment by sidferreira** [comment]
@fzaninotto Man, I'm feeling stupid... But the issue is back.
And now I'm even logged in.
It feels like the routing system doesn't identify the route, because even Redux isn't being called.
