### ISSUE TITLE
Pagination in tabbed list view

### ISSUE THREAD

**Issue by astoimenov** [marmelab/admin-on-rest#1064]
Hi,

I'm trying to create tabbed list view where I have a filtered list of users in every tab. The problem is that the pagination on the bottom is one for all tabs it doesn't change. When I use it it tries to change the page of all tabs.

What I did is to put List in every Tab and I have a Datagrid in the List.

Is there anything I can do for the pagination?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
