### ISSUE TITLE
SimpleList rightIcon click taking to editing page

### ISSUE THREAD

**Issue by astriskit** [marmelab/admin-on-rest#1070]
Hello guys. 

So, recently I upgraded my AOR based app to 1.3.0. As I browsed the mobile version in my mobile( using Chrome), the "rightIcon" was not working as was expected. It would take me to the editing page of that resource-item rather than opening the menu associated with "rightIcon". 

Any thoughts on fixing it or it might be a bug :) ??!

**Comment by fzaninotto** [comment]
Not sure what you mean by rightIcon. Can you provide a screenshot ?

**Comment by astriskit** [comment]
Oh! I mean't like this - 
`<SimpleList 
primaryText={record=>record.title} 
rightIcon={
 record=>(
    <IconMenu>
              <MenuItem primaryText="item-1"/>
             <MenuItem primaryText="item-2"/>
    </IconMenu>
   )
}
/>`
If it still needs a screenshot, I'd upload one!!
This is value of 'small' prop in Responsive Component.

**Comment by djhi** [comment]
That's because the `ListItem` components inside `SimpleList` are links to the resources.

You have two options here:

- Implement your own `SimpleList` component by copy/pasting the default one and removing the [link part](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/SimpleList.js#L41).
- Ensure that when the `IconMenu` is clicked, the event propagation is stopped so that it does not bubble up to the link.

**Comment by astriskit** [comment]
I see that now.
And my question is how in normal flow of developing an AOR based app, one would be able to use "rightIcon" prop.
In summary, how useful is rightIcon prop in current stage of AOR ?! 
:)

**Comment by fzaninotto** [comment]
Just pass an icon component, don't try to override the link there.
