### ISSUE TITLE
Pass custom params on create/edit form

### ISSUE THREAD

**Issue by siddushar** [marmelab/admin-on-rest#1074]
i have upload button inside create form, on button click handler i will upload image to cloud and on upload success i get image url. i need to pass this image url to rest api. this is my sample code.
When i submit my form i need to send image url as parameter.
Can anyone help me.

Here is my code:
`<SimpleForm label="Create Artist"> <TextInput source="name" label="Name" />
             <FlatButton style={styles.button} label="Upload Image" primary  onClick={this.handleClick} />
         </SimpleForm>`
    this.handleClick = () => {
      cloudinary.openUploadWidget({ cloud_name: 'demo', upload_preset: 'sh3432',  cropping: 'server' },
        function(error, result) {
          // i will get uploaded image url
        });
    };

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
