### ISSUE TITLE
Set up project in IDE's

### ISSUE THREAD

**Issue by gephaest** [marmelab/admin-on-rest#1096]
Probably there isn't AOR issue, but I could not solution.

After reading [guide](https://marmelab.com/admin-on-rest//Tutorial.html#installation) I had been configure app, but IDE's (IDEA based like WebStorm/PHPStorm and VSCode) can't resolve imports from admin-on-rest, but react imports works well. WebStorm says `Cannot resolve symbol %component_name%`

So what I should set up to get full IDE autocompletion?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by afilp** [comment]
@gephaest @djhi I have the same problem, isn't this an "issue"? I mean, should the code have something different so that te IDEs (like IDEA) can resolve the AOR symbols?

See here for example, no imported symbols can be resolved:
![image](https://user-images.githubusercontent.com/7850073/35246602-f11e1c34-ffcf-11e7-93b7-4103e88ee652.png)

Thanks!

**Comment by djhi** [comment]
I don't how IDEA works. What I can tell you is that I don't have any imports problems in vscode: I even get autocompletion for them

**Comment by tkvw** [comment]
@afilp : you can add 
```
    "jsnext:main": "src/index",
```

to the package.json of `react-admin` (so editing the entry in `node_modules/react-admin/package.json` for IDEA to get autocompletion. IDEA can't handle dynamically named es5 modules. (I created an issue for this on the IDEA issue list, and this is currently the workaround)

**Comment by mark-anders** [comment]
Thanks, @tkvw !  I added it so that my file had this, as I wasn't sure if `jsnet:main` replaced or augmented `main`.

    "main": "lib/index",
    "jsnext:main": "src/index",
    "scripts": {

Anyway, that fixed it!

**Comment by kitburgessV** [comment]
Adding

```
"jsnext:main": "src/index",
```

to the `package.json` of `admin-on-rest`, rather than `react-admin` worked for me

**Comment by m4nu56** [comment]
I encounter the same problem with Intellij IDEA, adding 
`"jsnext:main": "src/index",`
to the `package.json` of `node_modules/ra-core` didn't change anything for me. Any idea ?

**Comment by Benew** [comment]
+1 here @fzaninotto asked a question on SO https://stackoverflow.com/q/54118304/1491212
