### ISSUE TITLE
CreateForm & EditForm doesn't redirect to list.

### ISSUE THREAD

**Issue by kamalk333** [marmelab/admin-on-rest#1101]
I'm using admin-on-rest for budget tracking. If I want my admin panel to switch back to last year then I render data on the grid accordingly. 

Our client wants a feature to hide Create Button and Edit button from the admin panel, if the data belongs to last year, else show as it is.

I tried to change my code in App.js something like this.
This code worked and I just tried with createform. But the moment I try to save the form the routing to list doesn't take place. 

If(isCurrentyear){
    '<Admin
      authClient={authClient}
      theme={getMuiTheme(Customtheme)}
      dashboard={Dashboard}
      title="Hellow World"
      restClient={jsonServerRestClient(API.BASE_URL)}>
          <Resource
             name="users"
             options={{ label: 'Users' }}
             list={UserList}
             create={createUser}
             edit={editUser}
             remove={Delete}
             icon={userIcon}
          />
     </Admin>
}else{
   <Admin
      authClient={authClient}
      theme={getMuiTheme(Customtheme)}
      dashboard={Dashboard}
      title="Hellow World"
      restClient={jsonServerRestClient(API.BASE_URL)}>
         <Resource
             name="users"
             options={{ label: 'Users' }}
             list={UserList}
             edit={editUser}
             remove={Delete}
             icon={userIcon}
         />
     </Admin>
}

> 

if there's any other optimum solution. Please guide me.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
