### ISSUE TITLE
Controll admin reducer

### ISSUE THREAD

**Issue by huynguyenh** [marmelab/admin-on-rest#1102]
Hi, thanks for your greak work

I'm sorry in advance if i miss this part in document.

My question is  there any way i can dispatch an action to manipulate the admin reducer to update a record data

Thanks

**Comment by schmanat** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
