### ISSUE TITLE
Datagrid does not support in mobile.

### ISSUE THREAD

**Issue by taweesoft** [marmelab/admin-on-rest#1103]
When I try to view list from my mobile. I cannot scroll to the right even my list still has columns.
I have tried in demo project also.

<img width="379" alt="screen shot 2560-09-28 at 11 38 10" src="https://user-images.githubusercontent.com/8603253/30949638-d02e93f8-a441-11e7-9b41-cee9e5ca4839.png">

It looks like Table from material-ui fix `overflow-x: hidden` and I try to override the style according to this link http://www.material-ui.com/#/components/table both style and wrapperStyle and it does not work.

**Comment by taweesoft** [comment]
I know there is SimpleList but I would like to show Datagrid and table in mobile view. Is there any solution ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by data-server** [comment]
Is there any solution? still does not work

**Comment by data-server** [comment]
@taweesoft

**Comment by djhi** [comment]
The solution is to make your own component: https://marmelab.com/admin-on-rest/List.html#using-a-custom-iterator
