### ISSUE TITLE
How to display existing array of data in a datagrid row?

### ISSUE THREAD

**Issue by apptomato** [marmelab/admin-on-rest#1105]
Sorry, but can't find any solution in docs. For example I have resource "buildings", my rest server returns it like this:

[{"id": "123", "address": "Baker Street 221", "apartments": [{"id": "1", "name": "Sherlock"}, {"id": "2", "name": "Watson"}] }}]

So, I have list in list. How can display apartments array? The ReferenceManyField is ok, but I don't need to fetch by rest request in case I already have the data. So I looking for something like:

<List {...props} >
        <Datagrid>
            <TextField source="address"/>
           <ListField source="apartments">
                <Datagrid>
                    <TextField source="name"/>
               </Datagrid>
           </ListField>
        </Datagrid>
    </List>

Many thanks!

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
