### ISSUE TITLE
Custome Inputs

### ISSUE THREAD

**Issue by samanmohamadi** [marmelab/admin-on-rest#1110]
I have a User Resource, which referenced by many other resources.  
So I want to create a UserResourceInput :

    import React from 'react';
    import {ReferenceInput, SelectInput} from 'admin-on-rest';
    
    
    const UserReferenceInput = (props) => (
        <ReferenceInput reference="user" {...props}>
            <SelectInput optionText="name"/>
        </ReferenceInput>
    );
    UserReferenceInput.defaultProps = {
        source: 'userId',
        addLabel: true,
        label: 'User'
    };
    
    export default UserReferenceInput;

And Use it in simple form like this:

    ProductCreate = (props) => (
        <Create {...props}>
            <SimpleForm>
                <TextInput source="title" />
                <NumberInput source="price" />
                <UserReferenceInput />
            </SimpleForm>
        </Create>
    );

But I get this Error:
[![enter image description here][1]][1]

[Question in stackoverflow](https://stackoverflow.com/questions/46492471/admin-on-rest-customizing-inputs)

  [1]: https://i.stack.imgur.com/oQPT6.png

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

Please don't double post here and on SO. It doubles the work for us

**Comment by samanmohamadi** [comment]
Your right but I thought it could be a bug so I posted it here.

**Comment by djhi** [comment]
Found the problem and answered on SO.

Also see: https://github.com/marmelab/admin-on-rest/issues/896
