### ISSUE TITLE
How to safely transform list params filter before requesting the server

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1127]
I am looking at admin-on-rest source code to establish the possibilities we have to communicate with our backend.

We use spring-data and querydsl, because of that, we don't have much flexibility on how we can receive these filter params.

They should be `?username=foobar`
Instead of `?filter={ username: 'foobar }`

I am not sure for us if our best option is to fork and work on our side, or if there is a better way to hook the request process and update the request without changing how `changeListParams` and `query` works.

Version: 1.3.1

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
