### ISSUE TITLE
storing data into database using ReferenceArrayInput

### ISSUE THREAD

**Issue by donno13** [marmelab/admin-on-rest#1152]
i have three models in loopback which are loyaltyTiers, loyaltyEarnRules and loyaltyEarnRuleMap which is related as loyaltyTiers hasMany loyaltyEarnRules through loyaltyEarnRuleMap .In ui in loyaltyEarnRules  i am fetching data from a coloumn tierName which belongs to loyaltyTiers using ReferenceArrayInput .i am able to have a multiselect option there.but at the click of save button i want to store these multiselected tierName into  loyaltyEarnRuleMap. how do i save that multi-selected data . Please  somebody help me . thankyou in advance
 this is the piece of code i am working on 

<ReferenceArrayInput source="loyaltyTierId" reference="LoyaltyTiers" label= "Tier Name" allowEmpty >
              <SelectArrayInput optionText="name" />
            </ReferenceArrayInput>

**Comment by vedmalex** [comment]
I think you need to make it on server-side.

**Comment by donno13** [comment]
I dint get can you be little specific .thanks for being so responsive

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
