### ISSUE TITLE
allowEmpty mandatory on Create form using a ReferenceInput

### ISSUE THREAD

**Issue by Phocea** [marmelab/admin-on-rest#1153]
**What you were expecting:**
Using `ReferenceInput` inside a `Create` `Simpleform` to work without having to use the `allowEmpty` prop

**What happened instead:**
The component is disabled

**Related code:**
https://codesandbox.io/s/52o4m4pxo4

**Other information:**
To be able to enter a resource with a mandatory `ReferenceInput`, there is no other choice than to use the allowEmpty prop in the `Create `config. Which is very contradictory, specially together with `validation={{ required: true }}`

Since there is no reference id yet, and allowEmpty is false, this piece of code is executed in `ReferenceInput`

```
            if (!referenceRecord && !allowEmpty) {
                return _react2.default.createElement(_Labeled2.default, {
                    label: typeof label === 'undefined' ? 'resources.' + resource + '.fields.' + source : label,
                    source: source,
                    resource: resource
                });
            }
```
and the dropdown is deactivated

![image](https://user-images.githubusercontent.com/724262/31545344-4635c1fa-b01f-11e7-9337-4a73b6b975f8.png)

Could we change this condition and not do this if we are on a create form maybe ?

**Environment**

* Admin-on-rest version: 1.3.1
* React version: 15.6.1
* Browser: Chrome

**Comment by fzaninotto** [comment]
We've used `allowEmpty` erroneously, and this has this kind of side effects. Here is what I think.

Reminder: `allowEmpty` adds an empty choice in the choices list, with a value of `null`

## SelectInput

**Non-nullable field**: `allowEmpty` *should not* be used. The Select can already have an initial null value, it’s supported by material ui without the need for an empty choice. 

**Nullable field**: `allowEmpty` *should* be used, but is not compulsory in Creation. As it adds a blank choice on top of the choices list, it’s not useful for *creation* (because the user can leave the input unchanged with a null value), but it’s necessary for *edition* (to allow the user to deselect a choice and switch to the null choice).

## ReferenceInput

In general, If the possible reference aren’t fetched yet, the component should show a loader instead of rendering its child. Here, `allowEmpty` is used in conjunction with `referenceRecord` to know if the fetching of the possible references is finished, and this has bad side affects. 

Just like for `SelectInput`: 

**Non-nullable field**: `allowEmpty` *should not* be used. 

**Nullable field**: `allowEmpty` *should* be used in Edition, *can* be used in Creation.

So the question remains about how to detect the end of the possible references loading without relying on `allowEmpty`. I suggest relying on `matchingReferences`, which should be `null` before and during the fetch, and contain an array once the fetch completes.

What do you think?

**Comment by Phocea** [comment]
So for ReferenceInput we would get a spinner prior to the actual element rendering properly. And as soon as fetch complete, the correct element will display ?

Sounds good to me !

**Comment by fzaninotto** [comment]
Exactly
