### ISSUE TITLE
Any chance of removing MaterialUI it as dependency ?

### ISSUE THREAD

**Issue by theodorDiaconu** [marmelab/admin-on-rest#1182]
Any chance of removing MaterialUI it as dependency ?

**Comment by djhi** [comment]
Thinking about it, maybe following the render callback way. Won't happen soon though

**Comment by fgiroud** [comment]
I understand this will not happen soon, and it's normal. But it would be very interesting if at least, List, Show, Create, Edit and Delete would be rid off `Card`, `CardText`, and `ViewTitle` components, so we could re-use re-use them if we include AOR in another app.


For me the most interesting part of AOR is what you have done with redux, sagas and authentication, this is just awesome, and I use it everyday:
- I included AOR in another application (without MUI, as you described in the doc)
- As a source of inpiration, because as far as I know, there is no better exemple on how to implement things the proper way
