### ISSUE TITLE
Support for runtime configuration

### ISSUE THREAD

**Issue by dili91** [marmelab/admin-on-rest#1185]
I'm quite sure this is not the right place to post this, but maybe someone here had the same problem

I built a docker image (based on official nginx image) to serve the **build** folder, result of `yarn build`. My problem is that I have a unique image to be used both on test and prod environments. I don't want to have different images for each environment, instead i'd like to leverage on containers startup configuration in order to run my container with test or prod configuration. That is, some kind of configuration decoupled from the build task which can be applied on top of a build

The reason is that there are no differences between the 2 environments, except for my backend endpoint which is used by my custom http client inside admin-on-rest app.

Is there a support for this kind of configuration or should I implement something like [this](https://github.com/angular/angular-cli/issues/3855#issuecomment-274803729) ?

Thanks

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
