### ISSUE TITLE
Losing changes on save

### ISSUE THREAD

**Issue by sidferreira** [marmelab/admin-on-rest#1190]
Hi guys!
I need a help here cause this error may be related to `redux-form` or something, but I'll describe as clearly as possible.

My issue is: When I hit the "save" button, any field that CHANGED, that's not new, will have the value reset to the previous value.

Just in case I updated AOR to the latest version (1.3.2) and it still happens.
I tried to debug the restClient, but it already receives the values reset.

This issue is really new to me and I have no idea what it might be.

What more information can I offer to figure this out?

**Comment by fzaninotto** [comment]
Hi Sid, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
