### ISSUE TITLE
REST response must contain a data key

### ISSUE THREAD

**Issue by samanmohamadi** [marmelab/admin-on-rest#1194]
why admin on rest doesn't accept response with 204 status and empty body for DELETE requests?

**Comment by fzaninotto** [comment]
admin-on-rest doesn't have any rule regarding the HTTP response. It lays out a request/response format of what it needs, and it's your job to map that to your API grammar using a restClient.

https://marmelab.com/admin-on-rest/RestClients.html

Also, for asking questions please use StackOverflow. this tracker is for bug reports only.

**Comment by jtrein** [comment]
I may open an issue. I think it's a bug.

https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/src/sideEffect/saga/crudFetch.js#L28

Maybe it's doing exactly what you want it to, but the `Error` message seems off, because there's already a `data` key. If not, I suggest some other logic in the `if {}` block.

Here's my workaround, for now.

```js
const httpClient = (url, options = {}) => {
  return fetchUtils.fetchJson(url, { ...options, credentials: 'include' })
    .then(({ body, headers, json, status }) => ({
      body,
      headers,
      json: json || {},
      status,
    }));
};
const restClient = jsonServerRestClient(config.server, httpClient);
```

**Comment by Kmaschta** [comment]
I confirm this check is still here on the `next` branch.
https://github.com/marmelab/admin-on-rest/blob/next/packages/ra-core/src/sideEffect/saga/crudFetch.js#L33

**Comment by fzaninotto** [comment]
> the Error message seems off, because there's already a data key present (baked-in) via the `jsonServerRestClient` code. If not, I suggest some other logic in the if {} block.

I don't understand this comment, can you elaborate? There is a `data` key in `jsonServerRestClient`, but developers can use their own rest client, and the `fetch` saga expects a certain format, so it has to check it anyway.

The format expected for a `CRUD_DELETE` request is a response with, in the `data` field, the deleted object. If your API doesn't return that, then you can just make that object client-side, with an `id` field - the one you just removed. 

```
{
  data: { id: 123 }
}

```

**Comment by jtrein** [comment]
We must have been trying to bend `jsonServerRestClient` to our will. The error message is fine, since it's checking any and all added REST clients.

I must have misunderstood how the system fit together. Is there somewhere in documentation I could help make better? It was difficult to find what exactly needed to be done on client or server, or customised to work correctly.

**Comment by fzaninotto** [comment]
I've pointed the relevant documentation in my first comment. 

You can also try the updated version in `next`, and propose improvements if it's not clear.

https://github.com/marmelab/admin-on-rest/blob/3881a3dc2dcfe0024c723ee1ca352268994a7c82/docs/DataProviders.md
