### ISSUE TITLE
Content disappear on page reload on Chrome

### ISSUE THREAD

**Issue by sebdec** [marmelab/admin-on-rest#1211]
On chrome browser only

**What you were expecting:**
Using the demo app: https://marmelab.com/admin-on-rest-demo/#/customers (i have the same trouble on my app)
I want to reload the customers list page and see the refreshed data

**What happened instead:**
The customers list disappear without errors in console
I have to log out and log in to retrieve the content of the page

**Steps to reproduce:**
go to https://marmelab.com/admin-on-rest-demo/#/customers on chrome
reload the page

**Related code:**
I had trouble to find the cause of this issue

**Other information:**
Same issue for the show and edit pages

**Environment**
* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue: **=> works fine in 1.2.3**
* React version: 15.5.4
* Browser: Chrome (Version 61.0.3163.100)
**=> works fine on Safari and firefox**
* Stack trace (in case of a JS error): No errors...

Any idea?
Thanks in advance

**Comment by malisbad** [comment]
I have this happening in my application as well. It appears to be that the redux store drops the application state. I don't have to log in/log out, I have to click on the resource tab in the sidebar so that AoR pulls down that resource from the backend.

This also happens if you link to a resource directly (e.g. `<host_url>/#/users/<user_id>`). You'll get an empty component because the state hasn't loaded via `GET_LIST`, and `GET_ONE` doesn't appear to work independently as per my #1212 issue.

**Comment by fzaninotto** [comment]
I have Chrome 61 as well, and I can't reproduce the issue.

- go to https://marmelab.com/admin-on-rest-demo/#/customers on chrome
- reload the page (using the Refresh button, right?)
- the list is still there

**Comment by sebdec** [comment]
it is due to a chrome plugin: [https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd](url)

thank you for having a look at that 👍, I close the issue

**Comment by ClarissaDP** [comment]
@sebdec  the link you sent is broken, I can't see what was the problem.
