### ISSUE TITLE
Custom sort mechanism for <List>

### ISSUE THREAD

**Issue by dili91** [marmelab/admin-on-rest#1215]
Is it possibile to implement a custom sort mechanism inside **<List>** component? 

I'm using AOR to build an ecommerce backoffice. My products entities have a SKU field, of type String, composed by a prefix of 2 chars and then an integer. Being a String, AOR is using alphabetical order I suppose. What i'd need is something different.

in my drinks <List> area i'd like to sort objects this way ASC: 
BI, B2, B10

Currently i have this order ASC :
BI, B10, B2

So my requirement is to create a custom mechanism to evaluate sorting. Is it currently possibile ? If not, could  this be considered as future improvement ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by afilp** [comment]
I assume this can mechanism be done only on the server side. Because the server decides "which 15 items to send", based on the sorting criteria. So, the code in server should interpret somehow a custom sort intention from the user and perform the "smarter" sort based on that intention.

If anyone could suggest a best practice on how to handle this I would appreciate it.

**Comment by fzaninotto** [comment]
See also #1755
