### ISSUE TITLE
Reference Field when Nested objects are serialized

### ISSUE THREAD

**Issue by BaptWaels** [marmelab/admin-on-rest#1219]
Hi, 

I've implemented my custom restClient to plug it to my Django REST Api. I'm able to render a Datagrid of my /projects endpoint. It contains a Nested object : project_master who is a user. 

Instead of returning an id of the user, it returns the serialized user directly. I've got the same behaviour for all my API, every nested objects are serialized directly.

```
<ReferenceField label="Project Master" source="project_master" reference="users">
      <EmailField source="email" />
</ReferenceField>
```

At the moment, I've solved my problem like this : 

`restclient.js`
```
const convertHTTPResponseToREST = (response, type, resource, params) => {
        const { headers, data } = response;
        switch (type) {
            case GET_LIST:
                const convertedData = convertNestedObject(resource, data.results);

                return {
                    data: convertedData,
                    total: data.count
                };
       
            default:
                return { data: data.results };
        }
    };


const convertNestedObject = (resource, data) => {
    switch (resource) {
        case "projects":
            return data.map(project => {
                return { ...project, project_master: project.project_master.id };
            });
        default:
            return data;
    }
};
```

Is there a way to specify my ReferenceField to get : project_master.id instead of project_master ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
