### ISSUE TITLE
CHANGE_LIST_PARAMS_ACTION action should trigger CRUD_GET_LIST action (or visaversa)

### ISSUE THREAD

**Issue by gunderjt** [marmelab/admin-on-rest#1232]
While refactoring `<List>`  component, realized that there were two calls which change the redux state `crudGetList()` and `changeListParams()`.  However, they both appear to be inextricably linked and both states don't need to managed separately.

I propose:

* CRUD_GET_LIST action should, by default, rely on the redux list params state as the one source of truth to determine the resource parameters.

* triggering CRUD_CHANGE_LIST_PARAMS, should also trigger the CRUD_GET_LIST action. Simplifying the list state management and minimize the likelihood that the list params and the ids are mismatched.

* As an alternative, we can update the list params state based on the crudGetList action payload.  Either way remove the multiple calls to update the redux list state.

I can create a PR if this sounds good.

**Comment by fzaninotto** [comment]
I don't understand your point. 

Everything works: In `<List>`, any user action (sort, change page, update filer) results in a dispatch of `CHANGE_LIST_PARAMS`. This updates the redux state related to the list *and* the URL, so the list gets rerenderd. The `List.componentWillReceiveProps()` methods then sees that some of the list params have changed, and dispatches the `CRUD_GET_LIST`.

So `CRUD_GET_LIST` always uses the Redux state as base.

If you have found a bug, please explain it and give a way to reproduce it. Otherwise. I don't see your point.
