### ISSUE TITLE
Redirect in authClient

### ISSUE THREAD

**Issue by congaductq** [marmelab/admin-on-rest#1246]
I have `authClient.js` file as below:

    export default (type, params) => {
    if (type === AUTH_LOGIN) {
        return UserLoginService.signIn(params)
    }
    if (type === AUTH_LOGOUT) {
        // ...
    }
    if (type === AUTH_ERROR) {
        // ...
    }
    if (type === AUTH_CHECK) {
        return localStorage.getItem('token') ? Promise.resolve() : Promise.reject({ redirectTo: '/no-access' });
    }
    return Promise.reject('Unkown method');};

In authentication services, after user signed up, I create temporary password and send it to user via email. I require user to change their password in the first login. 

In `UserLoginService.signIn()`, if it's the first login, I do this `reject({ code: 'NewPasswordChallenge' });`

Is there any way to redirect to `/change-password` page if type is `AUTH_LOGIN`? like when type is `AUTH_CHECK`?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
