### ISSUE TITLE
[RFC] Add an <AsyncResourcesData /> or a documentation on how async data loading can be done

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1247]
First of all, I want to excuse myself for asking again a sort of "How To" question.

We've been asking on stackoverflow for weeks without  getting an answers. And we got slowed writting poor quality code since we never clearly solved that issue.

*Also to support the time it cost to answer, I want to add that we are about to release a few front-end packages made for **admin-on-rest** (particularly if you don't wan't to use material-ui), if you want to give feedbacks or/and test you will be welcomed.*

**What you were expecting:**

So far, playing with `react-admin` was a real pleasure except when it comes to load async data in chain. This downside can quickly become a nightmare when we need to customize our front-end.

We loose a lot of time when we try to write components that requires many async operations.

Example: 

I want to display a list of checkbox with allowed `role` for `OAuthClient` resource, a `User` have many `OAuthClient`. 
2. `OAuthClient` have many roles.
3. `OAuthClient` available roles depend on the list of roles the `user` currently have.

A possible solution would be to fetch data by starting (3) with a `ReferenceField` and use it's response so it can be available to the `Input` where we will use the data to customize the UX. this require to encapsulate the components like this

     Edit > ReferenceManyField > Grid > Input

This work fine but:

- That doesn't scale to more than 1 or 2 requests otherwise the JSX tree hierarchy will become a strange nested thing + we can't find meaningful names for all theses useless components.
- Conditional `if/else` statements will often need to be spitted in order to catch the data and the JSX tree will be written around that condition making the code poor and unreadable.

This is a bit of frustrating not being able to write quickly UX and to see our code getting split without any logic behind.

For async operations, I have been using for years [async](https://www.npmjs.com/package/async) which does exactly what we want, loading asynchronously many data.

Again, this is the 3rd time I ask the question and I feel sorry if it is already answered, I didn't understand how to do.

Also, if this is not possible with the current `react-admin`, would you be interested in such implementation?

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 16

**Comment by llioor** [comment]
Hi, @kopax .. Did you have a solution for it? I saw you close the case, did you open another one on stackoverflow?
Thank you,
Lior.

**Comment by kopax** [comment]
Hi @llioor. I decided to close because we didn't got any answers and contributors are currently working on a V2. I think this is not the right moment to bring this idea.

On my side, I didn't implemented it yet but I will.

This flow is not very usefull when you need to access a particular record in your JSX: 

1. `Edit`/`Show`/`Reference{Many|Array}Field` fetch one data 
2. `SimpleLayout`, `SimpleForm` receive the record and pass it to `field/input` and context, overriding any previous record in the context.

I concluded there is 4 way to access the record : 

- Using the context, but this require stupid code
- Writting `PageLayout`, `PageForm` and writting all the `Field/Input`, but this require to give up reusing our layout/form.
- Writing selectors and serv ourself in the store, but this require adminonrest not to break how it work internally and to communicate.
- Writing a `<AsyncLoader />` and `<AsyncMapper` />, the first would be in charge of loading many data at the image of `asyncjs` and the second would be in charge like `layout/form` to create a context for the multiples record. This will also require custom input with an additional field to name the record to be used by the field.

I personally chooses to do the latest solution as it seems to be the best available choice here.

I didn't know you were following, I'll reopen until I get maintainers opinion.

**Comment by llioor** [comment]
This is  avery professional answer. I know how to appreciate it. Thank you in advance ;)

**Comment by llioor** [comment]
I'll keep u posted. I will continue after the weekend ;)

**Comment by fzaninotto** [comment]
From what I understand, your problem isn't specific to admin-on-rest. You need to build a dynamic form based on various API calls. The solution is to build an Input component completely independent from admin-on-rest for that, and to use redux-form action creators to link your component to the Edit form. I wouldn't use Redux in your case, but rather a chain of Promises in `conponentWillMount()`.

As it's rather a general react question, I'll close it. Feel free to reopen if you think admin-on-rest goes in the way.

**Comment by llioor** [comment]
@fzaninotto actually I spoke about "load async data" for the <Admin> component is been displayed. For example I want to load the messages {en, fr...} in async request and  to show a spinner all over the screen before the <Admin> component is been loaded.. only after we have the "user locale" and "messages" (translations) we will display the <Admin> component.

I'm not sure if "custom app" is the solution here because it is a very requested feature (ability).

**Comment by nyejon** [comment]
Has there been any development on something like this? Or has anyone developed a solution I could use?

**Comment by fzaninotto** [comment]
@llioor react-admin supports async i18n messages out of the box, see https://marmelab.com/react-admin/Translation.html#changing-locale

**Comment by llioor** [comment]
Hi @fzaninotto 
I know about the i18n.
I'm talking about sending "an http request" to select the user "profile" in order to know which locale to set before the admin panel is displayed.
I imagine it like that:
1. "before display event"
2. Display loader all over the screen
3. Request and Response from a profile http request
4. Setting the user locale
5. Hide loader and Render the admin panel component 

Is it possible yet or not?
Thank you for the support.
Leo

**Comment by djhi** [comment]
@llioor There's nothing specific to react-admin in your usecase. Besides, as explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I invite you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
