### ISSUE TITLE
Custom action doesn't update element properties

### ISSUE THREAD

**Issue by houssemFat-DDF** [marmelab/admin-on-rest#1270]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
I'm trying to make a custom action (like approve Button in the demo for review). I expect to update the number of user  who vote for this element. If i make vote for example, i expect to increment the value of votes_count by one.
**What happened instead:**
The  state property was changed, but votes count did'nt changed. I tried even to modify the other properties but it does'nt works.

**Steps to reproduce:**

**Related code:**

###### Actions.js
```
import {UPDATE} from 'admin-on-rest';
export const REVIEW_APPROVE = 'REVIEW_APPROVE';
export const REVIEW_APPROVE_LOADING = 'REVIEW_APPROVE_LOADING';
export const REVIEW_APPROVE_FAILURE = 'REVIEW_APPROVE_FAILURE';
export const REVIEW_APPROVE_SUCCESS = 'REVIEW_APPROVE_SUCCESS';

export const reviewApprove = (id, data, basePath) => {
    return ({
        type: REVIEW_APPROVE,
        payload: {id, data: {...data, status: 'accepted'}, basePath},
        meta: {resource: 'features', fetch: UPDATE, cancelPrevious: false},
    });
};

export const REVIEW_REJECT = 'REVIEW_REJECT';
export const REVIEW_REJECT_LOADING = 'REVIEW_REJECT_LOADING';
export const REVIEW_REJECT_FAILURE = 'REVIEW_REJECT_FAILURE';
export const REVIEW_REJECT_SUCCESS = 'REVIEW_REJECT_SUCCESS';

export const reviewReject = (id, data, basePath) => {
    return ({
        type: REVIEW_APPROVE,
        payload: {id, data: {...data, status: 'rejected'}, basePath},
        meta: {resource: 'features', fetch: UPDATE, cancelPrevious: false},
    });
};

```
###### List component 
```
<List {...props} filters={<ReviewFilter />} perPage={25} sort={{ field: 'date', order: 'DESC' }}>
        <Datagrid rowStyle={rowStyle}>
            <TextField source="description" />
            <NumberField source="votes_count" />
            <TextField source="title" />
            <ApproveButton style={{ padding: 0 }} />
            <EditButton style={{ padding: 0 }} />
        </Datagrid>
    </List>
```
###### Server post request response
```
{"title":"1512643581296","description":"descritpion","status":"accepted","votes_count":1}
```
**Other information:**
[image item list] (https://imgur.com/a/y0vqX)

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.1.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
