### ISSUE TITLE
Infinite progress loader (handleFetch has been cancelled)

### ISSUE THREAD

**Issue by andrew-makarenko** [marmelab/admin-on-rest#128]
Hello! I did a simple setup of the project as described in the tutorial and face this kind of error:

After I create/update a record the loading indicator doesn't disappear.

Looks like the admin.loading counter is broken, because FETCH_END was called incorrect number of times. btw, I see the `handleFetch has been cancelled` warning in the console.

This type of bug is reproduced by me using the latest package ("admin-on-rest": "^0.4.0") and using different api clients (i tried jsonServerRestClient and a custom one).

I will appreciate any help, thanks in advance!

**Comment by hereischris** [comment]
Same for me with a custom Rest Client

**Comment by fzaninotto** [comment]
I think it's already fixed on master. Could you test with a checkout of the HEAD?

**Comment by hereischris** [comment]
Yep, works. Thank you. But i have to say that the build process is a bit bumpy if I want to use the HEAD status my (Node-) App. I tried to use npm for installation from github, but unfortunately, no Makefile was installed. I'm assuming the reason is the "file" declaration in the package.json but it's more a guess at the moment. 
Another solution could be to (Patch-) Release more often. Anyway, great work.

**Comment by fzaninotto** [comment]
v0.5.0 is now out. We make one release per month, it's already a lot.
