### ISSUE TITLE
Rendering one element on Chrome - cross-browser issue

### ISSUE THREAD

**Issue by ClarissaDP** [marmelab/admin-on-rest#1325]
Hi! 

I'm using [admin-on-rest](https://github.com/marmelab/admin-on-rest) which is working perfectly on Firefox, but not on other browsers. 

I've done every step as the documentation suggests, got the newest version so far and tried to search in the opened issues and stack overflow for a similar problem. 

It seems to be a problem with cross-browser implementation or documentation with admin-on-rest.

**What is happening:**

The main problem is that for some browsers, mainly Chrome, it works fine until I try to GET_ONE or UPDATE resource. It gets the correct response, tries to render and then gives an **Element does not exist** error, returning to previous page (LIST). 

[admin-on-rest Problem Video](https://youtu.be/L2ufzZ1tHew)

**Steps to reproduce:**

I created a fake account so you could test it 

e-mail/username: testador@adminonrest.com
password: 123mudar 

I still didn't implement the aor-permissions, so the view is still showing you can do everything, but is blocked from the back-end. But the problem shows when any user tries to get any single component. Try this:

* Scores -> _show_ (any element)

It gives Status code: 200 OK, it renders and fails, going back to the previous page.

**Other information:**

I'm using admin-on-rest with a custom restClient [ restClient={myApiRestClient('http://localhost:3000/v1', httpClient) ], which seems to be fine, seen that the request runs out ok.

**Environment**

* Admin-on-rest version: "^1.3.2"
* React version: "^15.6.2"
* Browser: **Chrome, Chromium** and **Opera**

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by ClarissaDP** [comment]
I sent as an issue because it didn't seem as a "How To" question, but as a problem. Because this is not specifies in any type of documentation or anything.

I will create the question on StackOverflow. Thank you.

**Comment by fzaninotto** [comment]
I'm qualifying as a how-to question because I can't reproduce it on Chrome, so I believe the problem is on your side.
