### ISSUE TITLE
Need a way for user to add / remove columns from table.   

### ISSUE THREAD

**Issue by kasajian** [marmelab/admin-on-rest#1386]
I need a way for user to add / remove columns from table in Admin-on-rest

This is for when the user has too many columns and wants to see a smaller number of them by default, but add new columns dynamically.

Can it be done?

**Comment by mattaylor** [comment]
It can be done, but it is not pretty. I wrote a 'columnselector component' which opens a checkbox list popover from a card actions menu button. When a column is unselected the css style the header and column cell for each row of the table is set 'none' . 

You would prob however be better off rolling your own grid using https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/uncontrolled-mode/

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
