### ISSUE TITLE
Overflowing Content issue(s)

### ISSUE THREAD

**Issue by yoonwaiyan** [marmelab/admin-on-rest#139]
I have updated the package and implemented a show page for a resource but seems like the entire content is not scrollable. I'm unable to view all my associated records and the table is not resizing when I docked my Chrome devtools to the right side(because the content is not scrollable I have to dock it to the side). I think this is not an issue from Material UI..

**Comment by fzaninotto** [comment]
Weird. I can't reproduce the issue on the demo, I can scroll vertically:

![scroll](https://cloud.githubusercontent.com/assets/99944/20269536/d0a43896-aa83-11e6-841a-586e8b2d7686.gif)

Could you share minimal code to reproduce the issue?

As for the table not resizing, perhaps it's because table cells now expand to fit the entire content. If you have large content for one field, the related column will enlarge the entire table. Try fixing this cell's width.

**Comment by yoonwaiyan** [comment]
Oh it was a styling issue from my local stylesheet, accidentally set overflow to hidden. 

![admin-on-rest](https://dl.dropboxusercontent.com/u/44973355/Nov-15-2016%2021-20-36.gif)

For the overflowing table, the problem is not about having large content of one field but rather for tables that have many fields(let's say I have more than 10 columns of fields to display) then I think it's not practical to set width to only 100px for each column. Maybe style the content to be able to scroll horizontally to avoid the white space on the right side? 

Btw, is there a way to hide the left sidebar(e.g. the menu toggle on the Appbar)?

**Comment by fzaninotto** [comment]
As for the table not being to display a large number of column without taking more width than the available screen size, that's normal. HTML tables work the same.

Material UI doesn't offer the ability to hide the sidebar without having it overlap the main content when it's open. So until they fix that, you'll have to come up with your own solution.

**Comment by dinushadev** [comment]
I am having the seam problem. Can you tell me how it resolve?

**Comment by keermanish** [comment]
is there any workaround (some props) to avoid full-screen horizontal scroll?
