### ISSUE TITLE
No date disable option available for DateInput!

### ISSUE THREAD

**Issue by devqualwebs** [marmelab/admin-on-rest#1400]
Their is no option available to disable date or start date and end date. If I want to restrict user for selecting future date in order to select date of birth, Their is no functionality available for this.

**Comment by djhi** [comment]
Hi, thanks for taking the time to report what you are perceiving as a lacking feature. There are actually options for that but github isn't the right place to answer the underlying question you're asking.

Can you please reformulate your issue as a question and post it on StackOverflow (http://stackoverflow.com/questions/tagged/admin-on-rest) then post the link here. I'll happily answer it there so that it will be easier to find for others. Indeed, this makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
