### ISSUE TITLE
content overflowing , not ellipsing 

### ISSUE THREAD

**Issue by cAstraea** [marmelab/admin-on-rest#144]
As seen here 
![image](https://cloud.githubusercontent.com/assets/13070662/20304167/8a3808c4-ab37-11e6-9258-59ebbfc5ad9a.png)

Tried to apply custom style on the <TextField /> without success

**Comment by fzaninotto** [comment]
Your URL requires a password. If it's an image, try pasting it directly in the issue description.

**Comment by fzaninotto** [comment]
How did you apply the custom style? It works on the [example](https://github.com/marmelab/admin-on-rest/blob/f311a0c44dac6849c342639773b1390ea572802d/example/posts.js#L35):

```js
export const PostList = (props) => (
    <List {...props} filter={PostFilter}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="title" type="email" style={{ display: 'inline-block', maxWidth: '20em', overflow: 'hidden', textOverflow: 'ellipsis' }}/>
            <DateField source="published_at" style={{ fontStyle: 'italic' }} />
            <TextField source="views" />
            <EditButton />
            <ShowButton />
        </Datagrid>
    </List>
);
```

**Comment by cAstraea** [comment]
Ah yes indeed playing with the maxWidth helps. I think my problem was similar to yoonwaiyan's

**Comment by alexborisov** [comment]
Hey I get this as well. It looks like the issue came with the new tables for the `DataGrid`. Basically if you have a wide grid (I have 6 columns, @cAstraea has a wide body column) and you size the browser window so that the grid goes offscreen then scrolling to the side you will see this issue. It looks like the table overflows the body container because it won't scale down. The body tries to maintain 100% of the screen and this causes the issue.

An instant solution that comes to mind is to wrap the `<table>` in a div and set it to `overflow-y: scroll` 

![screen-shot-2016-11-16-at-09 37 03- 2](https://cloud.githubusercontent.com/assets/721106/20342039/b29e9522-abe0-11e6-86f6-b46a8bf77e19.jpg)

**Comment by sahilbyjus** [comment]
> How did you apply the custom style? It works on the [example](https://github.com/marmelab/admin-on-rest/blob/f311a0c44dac6849c342639773b1390ea572802d/example/posts.js#L35):
> 
> ```js
> export const PostList = (props) => (
>     <List {...props} filter={PostFilter}>
>         <Datagrid>
>             <TextField source="id" />
>             <TextField source="title" type="email" style={{ display: 'inline-block', maxWidth: '20em', overflow: 'hidden', textOverflow: 'ellipsis' }}/>
>             <DateField source="published_at" style={{ fontStyle: 'italic' }} />
>             <TextField source="views" />
>             <EditButton />
>             <ShowButton />
>         </Datagrid>
>     </List>
> );
> ```

This is not working
