### ISSUE TITLE
Uploading multiple images on different fields

### ISSUE THREAD

**Issue by arkkanoid** [marmelab/admin-on-rest#1442]
Hi, 
I'm using the code that appears on https://marmelab.com/admin-on-rest/RestClients.html#decorating-your-rest-client-example-of-file-upload to upload an image to the server. But this code only returns multiple images on the same field.
How can I upload multiple images in different fields? 

    const addUploadCapabilities = requestHandler => (type, resource, params) => {
        if (type === 'UPDATE' && resource === 'posts') {
            if (params.data.pictures && params.data.pictures.length) {
                // only freshly dropped pictures are instance of File
                const formerPictures = params.data.pictures.filter(p => !(p instanceof File));
                const newPictures = params.data.pictures.filter(p => p instanceof File);
    
                return Promise.all(newPictures.map(convertFileToBase64))
                    .then(base64Pictures => base64Pictures.map(picture64 => ({
                        src: picture64,
                        title: `${params.data.title}`,
                    })))
                    .then(transformedNewPictures => requestHandler(type, resource, {
                        ...params,
                        data: {
                            ...params.data,
                            pictures: [...transformedNewPictures, ...formerPictures],
                        },
                    }));
            }
        }
    }

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
