### ISSUE TITLE
DateInput doesn't accept locales

### ISSUE THREAD

**Issue by augustomaia** [marmelab/admin-on-rest#1444]
**What you were expecting:**
The DateInput show months/days in English only, was expecting translation in case of **locales** attribute is set, like for DateField.

**This works**
<DateField source="date" label='Date' locales='pt-BR' />
Shows Day/Month/Year

**This doesn't work**
<DateInput source="date" label='Date' locales='pt-BR' />
Months and days are all in English

**Comment by djhi** [comment]
Indeed. This is explained in the documentation: https://marmelab.com/admin-on-rest/Inputs.html#dateinput

Use the `options` prop and follow material UI documentation: http://www.material-ui.com/#/components/date-picker

**Comment by afilp** [comment]
@djhi I am using 'next' that does not provide 'options'. Could we have 'options' there too?

**Comment by fzaninotto** [comment]
The `DateInput` uses the native `<input type="date" />` in `next` (that's a choice made by the material-ui team). This HTML element uses the browser locale, it does not support overriding the locale. We don't support it either.

But the dates should always display using the format expected by the user (since it uses the user's locale).
