### ISSUE TITLE
CustomRoutes refresh does not trigger `declareResources`.

### ISSUE THREAD

**Issue by santaclauze** [marmelab/admin-on-rest#1445]
**What you were expecting:**
Refreshing page from a  declared `customRoutes` using F5 and remaining in the same location and context.

**What happened instead:**
App crashes telling me: `Cannot read property 'list' of undefined`

**Steps to reproduce:**
I am not sure how to reproduce the error as I have other `customRoutes` that do not have the same issue

**Related code:**
First, I realized that in most other situations, or if I move the same routes from `customRoutes` to `Resource` just for the intention of testing the App would not crash. The bug seems to be inconsistent.

After logging in `initializeResources(children)` and within the `List` component, it seemed that `this.props.declareResources` was not called before the `List` component was mounted.

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable): N/A
* React version: "16.0.0",
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by santaclauze** [comment]
@djhi I believe that if what i encountered is true， this is not a question but rather a bug. 

I pointed out an unwanted behaviour that seems unexplained and related to the way admin-on-rest boots up.

**Comment by djhi** [comment]
Then we'll a codesandbox or a repository showing the issue

**Comment by santaclauze** [comment]
Here is a repo that uses your example that shows the issue.

https://github.com/santaclauze/aor-customRoutes-bug

## Steps to reproduce

1. npm install
1. make run
1. F12
1. Navigate between `http://localhost:8081/#/comments` and `http://localhost:8081/#/posts`

## Related Code

I created a `customRoutes` that I passed to the `Admin` component's prop customRoutes as stated in the documentation.

It contains the component `PostList` and `UserList` which I have moved from the `Ressource` components in `App`.

**Comment by kopax** [comment]
I went through the same diagnostics and I confirm this is a bug.

In every case, resources should be declared before all the routes, otherwise, none of the admin on rest components can work outside `<Resource />`.

It is possible to fix it by dispatching `declareResources`, but the fix should be in the lib.

There's only one reason maybe you didn't catch it earlier, you must never have used `customRoutes` with resources inside.

**Comment by djhi** [comment]
Ok, I see the problem now. This is indeed a breaking change we introduced in `1.3.0`. I'll see what we can do

**Comment by afilp** [comment]
I confirm that bug too.
