### ISSUE TITLE
Cannot read property 'split' of null on fetching

### ISSUE THREAD

**Issue by cAstraea** [marmelab/admin-on-rest#145]
After trying out the example with the jsonplaceholder data tried to integrate it with my own JSON but getting this message. Is there an issue with my data? 
![image](https://cloud.githubusercontent.com/assets/13070662/20311323/01ae42a4-ab58-11e6-960d-075016524c14.png)

**Comment by tr33m4n** [comment]
Hi there,

Are you using the simple rest client or your own? This is caused by the convertHTTPResponseToREST function attempting to parse a header that's not present in your response.

You will have to modify the headers your API returns or create a custom REST adapter http://marmelab.com/admin-on-rest/RestClients.html

Cheers

**Comment by cAstraea** [comment]
Hello, I was using the jsonServerRestClient , just modified the back end  to match the jsonplaceholder one and kept the same query string _sort, _order ,_start and _end 
Thought it would be enough. Will try to mimic the same response headers jsonplaceholder uses. 

For the moment just wanted to get GET_LIST working to test something really quick with my data. 
Thanks 🍰

**Comment by cAstraea** [comment]
I have added the total-count header yet it still reports the same ? What could I be missing
![image](https://cloud.githubusercontent.com/assets/13070662/20314899/9466c47a-ab64-11e6-97dd-b72c50bc3651.png)

**Comment by fzaninotto** [comment]
https://jsonplaceholder.typicode.com/posts does not have a `x-total-count` header, but
https://jsonplaceholder.typicode.com/posts?_page=1 does have it because it enables pagination.

When using JSONPlaceholder, you must add the pagination parameters to let admin-on-rest use it.

I'll update the default REST clients to fail more explicitly if the header is missing.

**Comment by fzaninotto** [comment]
Also, if you have added the `X-Total-Count` header but admin-on-rest doesn't see it, I guess it's because you're using CORS but you didn't declare the `X-Total-Count` in the `Access-Control-Allow-Headers` header.
