### ISSUE TITLE
Passing <TextField> value as a prop to <Approve> Button Component

### ISSUE THREAD

**Issue by mbj36** [marmelab/admin-on-rest#1461]
**What you were expecting:**
Is there any way to pass the row's column value as a prop to my approve button component ?
I want the id field value to be passed as a prop to my Approve component

**Related code:**
```javascript
import React from 'react'
import { List, Datagrid, TextField, getResources } from 'admin-on-rest'
import ApproveButton from './ApproveButton'

export const JobList = props => {
  return (
    <List {...props} title="List of Jobs">
      <Datagrid>
        <TextField source="id" />
        <TextField source="organisation_name" />
        <TextField source="job_title" />
        {/* <TextField source="job_description" /> */}
        <TextField source="employment_type" />
        <TextField source="job_location" />
        <TextField source="salary_range" />
        <TextField source="external_link" />
        <ApproveButton id={} />
      </Datagrid>
    </List>
  )
}
```

**Environment**

* Admin-on-rest version: 1.3.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by mbj36** [comment]
@djhi I could have asked in SO, but i have reached the question limit there

**Comment by djhi** [comment]
Take a look at the demo, we have this usecase with the `reviews` resource
