### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by samanmohamadi** [marmelab/admin-on-rest#1516]
After creation I get This error : 
![screenshot from 2018-02-11 13-07-44](https://user-images.githubusercontent.com/11535254/36071971-d5661c0a-0f2c-11e8-839d-5e615f15d16a.png)

**Response :**
```
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Total-Count
Access-Control-Allow-Methods: GET,HEAD,PUT,POST,DELETE
Content-Type: application/json; charset=utf-8
Content-Length: 183
Date: Sun, 11 Feb 2018 09:30:20 GMT
Connection: keep-alive

{
   "variants":[],
   "external":false,
    "id":19,
    "caption":"sdf",
    "src":"/public/media/images/02-18/B1rEpYpLf.jpg",
    "updatedAt":"2018-02-11T09:30:20.574Z",
    "createdAt":"2018-02-11T09:30:20.574Z"
}
```
originate from:
https://github.com/marmelab/admin-on-rest/blob/ff63e9ba8e18ee8c7bf7e4483a4a09d7fc60cdb4/src/sideEffect/saga/crudFetch.js#L28

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by x5engine** [comment]
@fzaninotto this is not a how to question bro, this is a bug

**Comment by djhi** [comment]
Then follow the issue template
