### ISSUE TITLE
different api call

### ISSUE THREAD

**Issue by muticansel** [marmelab/admin-on-rest#16]
Hi,

I'm using another api to list in Datagrid. But when I call it I'm getting an error as follows

![test](https://user-images.githubusercontent.com/32303129/40052245-1ed0e1ec-5846-11e8-81bd-31c534258be7.PNG)

The api that I use; https://reqres.in/api/products

Why do i get this error? Can you help me?
Thank you

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by muticansel** [comment]
Ok thank you

2018-05-15 15:02 GMT+03:00 Gildas Garcia <notifications@github.com>:
