### ISSUE TITLE
No way to set custom Page Title 

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1658]
When the Resource is set for an `Admin `component, the Title of the Main Page takes in the "**name**" passed to [Resource](https://github.com/marmelab/admin-on-rest/blob/master/docs/Resource.md#options). No way to customise that. Only Menu name is customisable.

Ex:
`<Resource name="v2/posts" options={{ label: 'Posts' }} list={PostList} />`

The Label "Posts" appears as part of the Menu correctly, but on right panel, the page title is rendered as **"V2/Posts"** i.e. it is taking the "name" property of the Resource. But if the Resource name is simple i.e. with no relative path syntax, 

`<Resource name="users" list={PostList} />` then the Page Title on right panel is rendered as _**Users**_

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

I'm inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
