### ISSUE TITLE
No options to pass the bulk data from one page to another page via route

### ISSUE THREAD

**Issue by santhosh1190** [marmelab/admin-on-rest#1670]
No options is given to pass  bulk data from one page to another page when click the route link.

**Comment by djhi** [comment]
Can you please explain your use case. It's very unclear

**Comment by santhosh1190** [comment]
Thanks djhi.. Here I have given clear content.

![admin-on-rest](https://user-images.githubusercontent.com/11721441/37599552-0d47cf7a-2bab-11e8-8106-d892225a1d05.png)


I have a list page with checkbox where we can select all the rows by using global checkbox or single row by using each row checkbox. I have button at top right corner **CUSTOM ACTION** which would take us to another page.

So After the select the rows from list, When I click **CUSTOM ACTION** button, I wanted all the selected rows ID's in next page.

**Comment by djhi** [comment]
Then its not an issue, it's an "How to" question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by afilp** [comment]
@santhosh1190 If you create a StackOverflow question there, please post the link here also, so that we can track the answer there too. Thx.
