### ISSUE TITLE
Custom authClient - Always AUTH_CHECK being called instead of AUTH_LOGIN

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1737]
**What you were expecting:**
I expect `AUTH_LOGIN` to be called the very first time and then subsequently `AUTH_CHECK` on every page load or context change

**What happened instead:**
I am getting `AUTH_CHECK`being called everytime so I had to repeat the code of `AUTH_LOGIN` in `AUTH_CHECK`. I do not have a login form, instead I need to delegate to my Auth URL and to do that on login compoment (see below), I can login action in ctor. Is that alright ?

**Related code:**
```
import * as React from "react";
import { connect } from 'react-redux';
import { userLogin as userLoginAction } from 'admin-on-rest';

declare namespace Auth {
    type Props = {
        userLoginAction: any
    }
}

class Login extends React.Component<Auth.Props, {}> {

    constructor(props : Auth.Props, context: any ) {
        super(props, context);
        const credentials = { };
        this.props.userLoginAction(credentials); // force login action, is this the correct place ?
    }

    render() {
        return (<div/>);
    }
};

const component = connect(undefined, { userLoginAction })(Login);
export = component;
```

```
import {AUTH_GET_PERMISSIONS,
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_ERROR,
    AUTH_CHECK} from "admin-on-rest";

const auth = (type:any, params:any) => {
        console.log(type);
        console.log(params);
        if (type === 'AUTH_LOGIN') {
            console.log('AUTH login...');
            const request = new Request('https://myUrl/token', {
                method: 'GET',
            })
            var response = fetch(request,{mode:'no-cors', credentials: 'same-origin'});
            return Promise.resolve('AUTH_LOGIN');
        }
        if (type === 'AUTH_LOGOUT') {
            localStorage.removeItem('token');
            localStorage.removeItem('role');
            return Promise.resolve("AUTH_LOGOUT");
        }
        if (type === 'AUTH_ERROR') {
            // ...
            console.log('AUTH_ERROR ...');
            return Promise.reject("AUTH_ERROR");
        }
        if (type === 'AUTH_CHECK') {
            console.log('AUTH_CHECK ...');

            const request = new Request('https://myURL/token', {
                method: 'GET',
            })
            var response = fetch(request,{mode:'no-cors', credentials: 'same-origin'});
            return Promise.resolve('AUTH_CHECK');
        }
        if (type === 'AUTH_GET_PERMISSIONS') {
            console.log('AUTH_GET_PERMISSIONS ...');
            //const role = localStorage.getItem('role');
            return Promise.resolve('AUTH_GET_PERMISSIONS');
        }

        Promise.reject('Unkown method');
    };

export = auth;
```

**Also, when does  AUTH_GET_PERMISSIONS gets called ?** - https://marmelab.com/admin-on-rest/Authentication.html#checking-credentials-during-navigation

```
    AUTH_GET_PERMISSIONS,
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_ERROR,
    AUTH_CHECK
```
-->

**Environment**

* Admin-on-rest version:1.4.0
* React version: 16
* Browser: Chrome

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by angshuman-agarwal** [comment]
Sorry, why is this an SO query? I see AUTH_LOGIN not being called at all with above auth client and login page implementation l.

**Comment by angshuman-agarwal** [comment]
https://stackoverflow.com/questions/49770746/aor-auth-client-auth-login-is-never-called
