### ISSUE TITLE
Cannot use two reference fields to the same resource

### ISSUE THREAD

**Issue by binhfoto** [marmelab/admin-on-rest#179]
Hi ,
I want to display more than one field of referenced record so I define like this

```
<List {...props} title="Storage List">

        <Datagrid>

            <ReferenceField label="Name" source="productId" reference="products">
                <TextField source="name"  style={GridStyle}/>
            </ReferenceField>

            <ReferenceField label="Unit" source="productId" reference="products">
                <TextField source="unit"  style={GridStyle}/>
            </ReferenceField>            

            <EditButton />

        </Datagrid>

    </List>
```

This one get error
`
bundle.js:2115 Warning: flattenChildren(...): Encountered two children with the same key, `584b7d3cdcb35d34e35640d2-productId`. Child keys must be unique; when two children share a key, only the first child will be used.
`

Are there any way to solve this?
I'm on version "admin-on-rest": "^0.5.4", and quite new to admin-on-rest.

Thank you very much.

**Comment by djhi** [comment]
You're referencing a product two times. The generated ids are the product ids. You should introduce a new Unit model

**Comment by djhi** [comment]
But that's a bug anyway. We'll look into it.

**Comment by djhi** [comment]
I misread your code. I'll check how to do that.

**Comment by binhfoto** [comment]
Thank djhi.

**Comment by fzaninotto** [comment]
While we could support that, you must be conscious that adding two reference fields tells admin-on-rest fetch the related object *twice*. That's not a good thing performance wise.

Until this is made possible (or until we make it impossible, I have yet to make up my mind), you can still display more than one field of the related object using the [`<FunctionField>`](http://marmelab.com/admin-on-rest/Fields.html#functionfield):

```
<List {...props} title="Storage List">

        <Datagrid>

            <ReferenceField label="Unit" source="productId" reference="products">
                <FunctionField source="name"  style={GridStyle} 
                           render={record => `${record.name} ${record.unit}` } />
            </ReferenceField>            

            <EditButton />

        </Datagrid>

    </List>
```

**Comment by MikeFair** [comment]
@djhi 

Please do not make this impossible; in fact expanding on the idea would make a really great UX feature.

It's quite common when linking objects to want to pull back more than one field to distinguish it.
Even better is to push beyond one hop so you can link to objects multiple hops away.
And the icing on the cake is would be multikey references.

I'd love to see some encapsulation method where you first updated the state for the Datagrid before it rendered.  Where the referenced objects would become named fields on the Datagrid's state.

Please forgive my lack of JsxReactFoo here; I envision something like this:
```
<List {...props} title="Storage List">
  <Datagrid
    ReferenceLinks={ [
        {"reference": "products", "link": {"productId": "proudctId"} },
        {"reference": "users", "link": { "userId": "ownerId"} },
        {"reference": "emergencyContacts", 
            "link": {"userId": "ownerId", "priority": "1"},
            "reference_name"="primaryContact"} 
        },
        {"reference": "emergencyContacts", 
            "link": {"userId": "ownerId", "priority": "2"},
            "reference_name"="secondaryContact"} 
        },
    ] }
  >
          <ReferenceField label="Name" reference="products">
                <TextField source="name"  style={GridStyle}/>
            </ReferenceField>
            <ReferenceField label="Unit" reference="products">
                <TextField source="unit"  style={GridStyle}/>
            </ReferenceField>            

            <ReferenceField label="Primary Name" reference="primaryContact">
                <TextField source="name"  style={GridStyle}/>
            </ReferenceField>            
            <ReferenceField label="Primary Phone" reference="primaryContact">
                <TextField source="phone"  style={GridStyle}/>
            </ReferenceField>            

            <ReferenceField label="Secondary Name" reference="secondaryContact">
                <TextField source="name"  style={GridStyle}/>
            </ReferenceField>
            <ReferenceField label="Secondary Phone" reference="secondaryContact">
                <TextField source="phone"  style={GridStyle}/>
            </ReferenceField>            

    <EditButton />
  </Datagrid>
</List>
```

Some way to encapsulate references as named objects before rendering to DataGrid.

With this kind of "referenceability" linking a record to all it's related "descendants" is very powerful.  

I'd personally want a secondary collapsible "row" below the record to display most of the extra details; but the point is that I could because I was able to modify the state of the record to aggregate in these extra reference_names before passing it down for rendering.

Thanks!!!
This framework is awesome!!

**Comment by fzaninotto** [comment]
Fetching references isn't the responsibility of the `<List>` or the `<Datagrid>`, it's the responsibility of a `Field` component. Prebrowsing all fields in the List to look for References is an anti-pattern (we've done this in ng-admin and it's a mess). 

So nothing is impossible ; in fact, you could probably implement more complex `<ReferenceField>` components yourself, even a `<TwoHopsReferenceField>`. Give it a try!

**Comment by MikeFair** [comment]
@fzaninotto 

Well first off, this is too awesome for me to say too much at the moment, but it's seems the `<Datagrid>` is missing that second dimension of `<ResourceItem>` that each row is describing.

The `<Field>` components in the grid, seem much more like a `<DataColumn>` of the Datagrid than a `<FieldItem>` of the Resource Record, but I might change my mind as I play with it more.  I've always found grids are kind of weird to properly express in a either a hierarchy or flat namespace because there's that dual nature of the "Row" that is both a specific renderable thing that hosts columns and an abstract data object to be rendered at the same time.


Each `<Resource>` described in the `<Admin>` object lives as part of a directed graph.
The thing I see missing, that's directly related here is a series of `<ResourceLinks>` that are children of the `<Resource>` object in the `<Admin>` component.

> Prebrowsing all fields in the List to look for References is an anti-pattern

I agree that prebrowsing through child nodes is an anti-pattern.  That's what that 'wall-of-text' "ReferenceLinks" object eliminates.  For each resource row it describes exactly what to fetch, where to fetch it from, how to fetch it (criteria to use), and where to stick the results once they arrive.  It links everything to the current record object (which the example assumes is "props").

With one pass through the ResourceLinks a "fetch chain" is memorized and on every row, all the link requests execute in parallel (with dependencies automatically triggering as the data comes back).


This is the only part that really makes me want to avoid using the feature:
> ... adding two reference fields tells admin-on-rest fetch the related object twice. That's not a good thing performance wise.


Other than that, I'm really looking forward to see what this can be made to do!

Thanks!!

**Comment by tilastokeskus** [comment]
+1 I really want this functionality. I want to make a "related data" view, where I can quickly see, for example,  the user who made a specific comment, without navigating away from the comment. I haven't come up with an alternative way, but for sure some kind of `RecordReference` component would solve this.

**Comment by Calcyfer** [comment]
+1 on this.

**Comment by afilp** [comment]
+1 on this too. While @fzaninotto suggestion of using a `FunctionField` is fine, this does not allow us to have 2 different columns on the datagrid, with separate sort, etc.

Would you consider implementing a solution?

**Comment by fzaninotto** [comment]
I've tested again, this works fine both on `master` and `next`. The `flattenChildren` error was fixed some time ago.

On mont, the `<ReferenceField>` component dispatches a `CRUD_GET_MANY_ACCUMULATE` action, which is accumulated and deduplicated by the `referenceFetch` saga. Once all the `<ReferenceField>` elements have finished mounting, the saga emits a single, aggregated, `CRUD_GET_MANY` action. 

This means that whatever the number of reference fields you have in a datagrid, they will be displayed correctly, without adding another request to the `restClient`.
