### ISSUE TITLE
[RFC] Intermediate layout component for `Edit`, `Create`, and `Show` views

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/admin-on-rest#216]
## Current status

Currently, the list view is composed of: 

- a data fetching component (`<List>`)
- a layout component (`<Datagrid>`)
- field components to configure the columns (`<TextField>` and others).

```js
const PostList = ({ props }) =>
  <List {...props} defaultSort={{ field: 'created_at', order: 'DESC' }}>
    <Datagrid rowStyle={(record) => ({ backgroudColor: !record.published_at ? 'red' : 'white' })}>
      <TextField source="title" />
    </Datagrid>
    </List>;
```

In contrast, the edit view is composed of:

- a data fetching component, also managing the layout (`<Edit>`)
- input components to configure the form inputs (`<TextInput>` and others).

```js
const PostEdit = ({ props }) =>
  <Edit validation={validationFunction}>
    <TextInput source="title" />
  </Edit>
```

As a consequence, implementing a custom form layout (tabbed, wizard, etc) is hard, and requires specializing the `<Edit> component.

## Suggestion

I suggest to make the API consistent, and require a form layout component between the `<Edit>` and `<Input>` components:

```js
const PostEdit = ({ props }) =>
  <Edit validation={validationFunction}>
    <SimpleForm>
      <TextInput source="title" />
    </SimpleForm>
  </Edit>
```

Alternatives to `<SimpleForm>` could be `<TabbedForm>`, `<WizardForm>`, or whetever layout component the developer feels like using.

## Impact

Writing an Edit view is slightly more verbose. But we had the same remark when [moving the layout out of `<List>`](https://github.com/marmelab/admin-on-rest/pull/22), and it hasn't created any real problem.

This is a major BC break, but it's the right time to do it since [the `next` version already breaks BC](https://github.com/marmelab/admin-on-rest/blob/6aa7e158aaa8e1bab43a44fba156618201bc545c/CHANGELOG.md).

What do you think?

**Comment by fzaninotto** [comment]
Elaborating on my previous proposal: which component should now carry the `defaultValue` and `validation` props?

Previously it was all the `<Edit>` component's job:

```js
<Edit defaultValue={{ foo: 'bar' }} validation={values => ({})}>
  ...
</Edit>
```

It makes sense to move the `validation` prop to `<SimpleForm>`, but I see no clear reason to put `defaultValue` in either one for the two:

```js
<Edit defaultValue={{ foo: 'bar' }}>
   <SimpleForm validation={values => ({})}>
    ...
   </SimpleForm>
</Edit>
```

or

```js
<Edit>
   <SimpleForm validation={values => ({})}  defaultValue={{ foo: 'bar' }}>
    ...
   </SimpleForm>
</Edit>
```

Here are my thoughts:

- `<Edit>` is responsible for fetching data. We could extend this to *preparing the data for the form*, and therefore it makes sense to keep `defaultValue` in `<Edit>`
- Default values are only useful in forms. No need to define them otherwise, so `defaultValue` should be in `<SimpleForm>`
- If the two props are spread in the two components, the developer might always wonder where to put `defaultValue`, and need to look at the documentation too often. so it makes sense to put them all in `<SimpleForm>`

What do you think?

**Comment by fzaninotto** [comment]
One more thought:

* Developers who want to reuse the same set of inputs for `<Edit>` and `<Create>` views can now do so by reusing the same form component. However, if the `defaultValue` prop is in the `<Edit>` or `<Create>` components, developers will have to *repeat* the default value, which is against the point.

This makes up my mind: I'm moving `defaultValue` to the form component.

**Comment by fzaninotto** [comment]
Fixed by #221

**Comment by sushanoup** [comment]
@fzaninotto trying to do   <Edit validation={values=>({
   
  })}
      {...props}
      /* disable the app title change when shown */
    >
but getting below error

React.Children.only expected to recieve a single React element child.

Any help is appreciated. thanks in advance

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- **Community support**: Ask your question on [Discord](https://discord.gg/MR9QFxMc). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.
