### ISSUE TITLE
Browse to Edit page after creating record

### ISSUE THREAD

**Issue by naibinh** [marmelab/admin-on-rest#301]
Hi,

Can we browse to List page after creating record instead of Edit page?
Why do we need to do as current behavior?

Regards and thank so much.

**Comment by fzaninotto** [comment]
Redirecting to the Edition view after creation is the default behavior because it makes sense in most of the cases. 

If you want another redirection, you'll have to write a [custom app](https://marmelab.com/admin-on-rest/CustomApp.html) to use your own version of [the `crudResponse` saga](https://github.com/marmelab/admin-on-rest/blob/927a0654f8e4da2818941e5f4c1bd4fbc945c8f9/src/sideEffect/saga/crudResponse.js). This is not documented, and requires goog knowledge of Redux and saga, but it's possible.

**Comment by rigobcastro** [comment]
Please make it modifiable <3

**Comment by djhi** [comment]
An easy way to do that (I just tested it) is to write a simple saga taking every `CRUD_CREATE_SUCCESS` actions and calling the `push` action creator using the action payload to compute the path. Just register the custom saga using the documented prop on the `Admin` component.

Note that this may trigger two navigation actions, the original one and the new one but it gets the job done.

**Comment by rigobcastro** [comment]
@djhi I will try it, thanks
