### ISSUE TITLE
Enable browserHistory option

### ISSUE THREAD

**Issue by gDelgado14** [marmelab/admin-on-rest#327]
`<Admin />` should be able to use more than just hashHistory.

**Comment by gDelgado14** [comment]
On a related note: Why is this repo using react-router v2? and why not v3? Just curious.

**Comment by fzaninotto** [comment]
Already discussed in #30: you can already do so by using a [custom app](https://marmelab.com/admin-on-rest/CustomApp.html). If `<Admin>` has to support all the options of Redux, react-router, saga, and translation, it will become a MONSTER 🐉 .

We're using v2 because this project started 6 months ago, and we're waiting for v4 to upgrade.
