### ISSUE TITLE
Many to many relationships

### ISSUE THREAD

**Issue by andreo** [marmelab/admin-on-rest#408]
What is a proper way to define many to many relationships?

**Comment by fzaninotto** [comment]
Since admin-on-rest provides no special system for it, you'll have to do it in React. This means querying the first table, then, upon reception of the response, query the second table.

You could easily do it [in a `componentWillMount()`](https://marmelab.com/admin-on-rest/Actions.html#using-the-rest-client-instead-of-fetch). If you're more adventurous, you could also do it with the Redux state. If you happen to go that far, please open a PR to let us benefit from your solution!

**Comment by leesei** [comment]
I'm looking into how to use the `crudGetMany` action. I think a good reference is https://github.com/marmelab/admin-on-rest-demo/blob/master/src/commands/Basket.js

Example:
https://marmelab.com/admin-on-rest-demo/#/commands/550?_k=80befq
This implements the basket on the right hand side where products are fetched with `crudGetMany` action.

**Comment by leesei** [comment]
Related: #429

**Comment by andreo** [comment]
How could an editable oneToMany list be implemented?

There are two actions:
1. Add related item
2. Delete related item

As I understand - a state of the items (new, deleted, unchanged) should be stored in the redux state (oneToMany). Then after "Save" button, the changes "new" and "deleted" are sent to the backend?

We can represetn the relation (A <-> B) as a separate resource (A_B): { a_id: 1, b_id: 3}
Or as an attribute-array.

**Comment by fzaninotto** [comment]
`ReferenceArrayField` and `ReferenceArrayInput` is as far as we'll get for now. I consider it solved.
