### ISSUE TITLE
How not to send an 'OPTIONS' request

### ISSUE THREAD

**Issue by teldosas** [marmelab/admin-on-rest#421]
I am trying to create an admin interface for a rest-api but since my server doesn't support the method 'OPTIONS' I get a network request failed. Is there any way to make admin-on-rest send directly the GET request without an OPTIONS request?

**Comment by fzaninotto** [comment]
The `OPTIONS` method is sent because your admin is hosted on another domain than the API (google CORS for details). Host them on the same domain and you should be OK.

Besides, admin-on-rest stops at REST requests. Transforming these into HTTP that work for your API is your responsibility (see [Rest Clients Documentation](https://marmelab.com/admin-on-rest/RestClients.html)).
