### ISSUE TITLE
Directly accessing resource link doesn't show the Data

### ISSUE THREAD

**Issue by rahul-iyer** [marmelab/admin-on-rest#497]
When I directly access the resource link (Eg : http://localhost:3000/#/form/101/show) or refresh the respective show page there is no data. When I see the network and see the response payload I find that the data has been received but its not being shown up on the UI.

The same perfectly works fine when I access it from the list page of the UI by clicking the show Button.

I think I am missing something but I am not able to understand as there are no error logs in the console.

Any heads up would be appreciated.

PS: I have customised the library to satisfy my needs.

**Comment by fzaninotto** [comment]
This must be linked to your customization, because it works on the blog example (e.g. http://localhost:8080/#/posts/13/show properly displays the post) and on the demo (check by yourself: https://marmelab.com/admin-on-rest-demo/#/commands/282).

If you customized your rest client, and updated to v0.9 recently, are you aware that the REST response format has changed?

https://marmelab.com/blog/2017/03/10/admin-on-rest-0-9.html#rest-client-change

**Comment by vysakh0** [comment]
@rahul-iyer Got the same issue, can I know how you fixed it please?

**Comment by rahul-iyer** [comment]
As @fzaninotto mentioned,I did not take care of the changes in restclient output.
You can get more info here: https://marmelab.com/blog/2017/03/10/admin-on-rest-0-9.html

 Type                 | Response format
 -------------------- | ----------------
 `GET_LIST`           | `{ data: {Record[]}, total: {int} }`
-`GET_ONE`            | `{Record}`
-`CREATE`             | `{Record}`
-`UPDATE`             | `{Record}`
-`DELETE`             | `{Record}`
-`GET_MANY`           | `{Record[]}`
-`GET_MANY_REFERENCE` | `{Record[]}`
+`GET_ONE`            | `{ data: {Record} }`
+`CREATE`             | `{ data: {Record} }`
+`UPDATE`             | `{ data: {Record} }`
+`DELETE`             | `{ data: {Record} }`
+`GET_MANY`           | `{ data: {Record[]} }`
+`GET_MANY_REFERENCE` | `{ data: {Record[]}, total: {int} }`
