### ISSUE TITLE
how can display author 's name in comments listview ?

### ISSUE THREAD

**Issue by huimingxie** [marmelab/admin-on-rest#54]
**how can display  author 's name in comments listview ?**

"comments": [
    {
      "id": 1,
      "author": {
        "name": "Luciano Berge"
      },
      "post_id": 5,
      "body": "While the Panther were sharing a pie--' [later editions continued as follows.",
      "created_at": new Date("2012-09-06")
    },
    {
      "id": 2,
      "author": {
        "name": "Annamarie Mayer"
      },
      "post_id": 5,
      "body": "I tell you, you coward!' and at once and put it more clearly,' Alice.",
      "created_at": new Date("2012-10-03")
    }
  ]

**Comment by fzaninotto** [comment]
It's fairly easy to create a custom Field component that handles this on your side. But since it's such a common requirement, I'll add a way to do it easily.

**Comment by alexborisov** [comment]
Hey thanks for adding this in. I've looked through the PR, but I can see there are still a few items in your todo. Any guestimate on an ETA?

**Comment by fzaninotto** [comment]
Nope. This is a voluntary project, and we have day jobs.

**Comment by alexborisov** [comment]
Fair play. I just wanted to know because I can do it the way you originally suggested with a custom component, but I saw you started work on it so if it was something that was coming really soon I could wait :) Thanks for the tool so far. It's really cool and actually a pretty nice example of how to do redux with side effects as well as how to structure a complex 'real world app'. It's hard to find much besides 'todo' apps which reminds me a [little of this](https://s-media-cache-ak0.pinimg.com/564x/75/4a/1d/754a1def902e9d60cbd631184106d883.jpg)

**Comment by fzaninotto** [comment]
Love the image. Yes, you're right, it's hard to find larger examples. We've struggled ourselves to understand (and sometimes [design](http://marmelab.com/blog/2015/12/17/react-directory-structure.html)) best practices in the Redux world.

**Comment by fzaninotto** [comment]
Fixed by #62
