### ISSUE TITLE
material-ui@next -- support timeline available?

### ISSUE THREAD

**Issue by onpaws** [marmelab/admin-on-rest#639]
`admin-on-rest` is a great project, thanks for your hard work here! 🎉 

Today I tried to change my app using admin-on-rest v1.0.0 to target [material-ui@next](https://github.com/callemall/material-ui/tree/next). However the API has changed enough to break many existing `admin-on-rest` components.
e.g. `styles/baseThemes/` no longer exists, and `svg-icons` has been pulled up into its own package:
![image](https://cloud.githubusercontent.com/assets/182515/25786484/23fa120e-3364-11e7-85a4-b488f8d6c5e4.png)

I saw[admin-on-rest@next](https://github.com/marmelab/admin-on-rest/blob/next/) and hoped it was a work in progress to target material-ui@next, but it targets [0.17.4](https://github.com/marmelab/admin-on-rest/blob/next/package.json#L63). 

Just wondering, is there a timeline on supporting material-ui@next?
How important is this considered to be compared to other efforts?

Thanks again for a great package here :) 
--
Also posted on SO
http://stackoverflow.com/questions/43838042/include-upstream-material-ui-into-admin-on-rest

**Comment by fzaninotto** [comment]
The next version of material ui is, as far as I understand, very much a work in progress. To date, there are 17 components not yet migrated (see https://github.com/callemall/material-ui/projects/1).

So admin-on-rest can't work with a version of a library that doesn't work.

admin-on-rest will probably use material-ui 1.0 several months *after* material-ui 1.0 is released as stable. Because that's a major rewrite.

Also, cross-posting on SO doubles our work, it's really not cool. So please delete your post back there.

**Comment by onpaws** [comment]
Thanks for the update. Several months at minimum, and only after they release. That's helpful to know - cheers!

Deleted the SO post.

**Comment by hongcai** [comment]
@fzaninotto Is there any plan to catch up with material-ui? They had v4.2.1 published, while we are still using v1.5.1

**Comment by djhi** [comment]
We use the v4 in react-admin v3. See https://github.com/marmelab/react-admin/issues/3194

**Comment by hongcai** [comment]
> We use the v4 in react-admin v3. See #3194

cheers~ looking forward to v3 release
