### ISSUE TITLE
[Feature] format for fields

### ISSUE THREAD

**Issue by wesley6j** [marmelab/admin-on-rest#685]
Currently, AOR supports `format` for inputs.

What about `format` for fields?

There is already `FunctionField` that can do this quite well, but having `format` props means the display logics in input can be reused.

**Comment by wesley6j** [comment]
Example here: [PR](https://github.com/marmelab/admin-on-rest/pull/686)

**Comment by leesei** [comment]
To clarify the terms, AOR's input are using `redux-form`'s `<Field>`, which supports [`format` prop](http://redux-form.com/6.7.0/docs/api/Field.md/#-format-value-name-formattedvalue-optional-). Note how it is used in [the value llife-cycle](http://redux-form.com/6.7.0/docs/ValueLifecycle.md/).
AOR's `<TextField>` is a `<span>`.

**Comment by wesley6j** [comment]
@leesei  I have no problem with the terms. 

The idea is that if you have a format prop for a  phone number `TextInput` , it feels natural that this same format props handles the format of the phone number's `TextField`:

```
// Create or Edit
<TextInput source="phone" format={phoneFormatter} />

// Show or List
<TextField source="phone" format={phoneFormatter} />
```
#686

**Comment by fzaninotto** [comment]
Except that some fields (`<DateField>`, `<NumberField>`) already support formatters through `options` relying on JavaScript's APIs. This type of formatting does not exist in the corresponding `Input` field. And I prefer to use browser APIs rather than custom ones (especially for such tricky problems as date and number formatting).

So it won't make sense to add a `format` prop to `<DateField>`, `<NumberField>`, which means that we won't add it to *all* fields.

Then, does it make sense to add it to *some* fields, or does it add confusion? Especially since, if all you're interested in is the `<Textfield>`, then the feature already exists: `<FunctionField>`...

**Comment by wesley6j** [comment]
Thanks for the explanation. I agree that it does not fit the project as it can not be applied to most of the fields.
