### ISSUE TITLE
[feature request] Add table footer on list page

### ISSUE THREAD

**Issue by mingchen** [marmelab/admin-on-rest#702]
For list page, data show in table may include a lot of data, it will be useful can have a table footer to do some calculate like sum() / average().

I hope it can expose and method to client can add custom table footer for this of usage.

**Comment by wesley6j** [comment]
You will need to fetch extra data in order to present useful information for the footer. That is how the pagination section of list page works. (Unless you want sum/average of currently displayed items?)

So it looks like your table footer requires more than a prop for `List` and it's better to write customised `List` and `restClient`.

**Comment by fzaninotto** [comment]
Agreed with @wesley6j: this is outside the scope of the admin-on-rest core components. But it should be fairly easy to achieve by writing your own `<Datagrid>` component.

**Comment by fab1an** [comment]
I vote to reopen this, since `TableFooter` is supported by material-ui `Table` component like `TableHeader` and `TableBody` is.

Aor already passes `headerOptions` and `bodyOptions`, so it just need `footerOptions` to create a footer. Thoughts on this?

**Comment by fzaninotto** [comment]
We'll reconsider this once we switch to material-ui 1.0. No ETA yet.
