### ISSUE TITLE
[Feature] required field asterisk

### ISSUE THREAD

**Issue by wesley6j** [marmelab/admin-on-rest#704]
Can we have 

- a `required` prop 
- or `label="resources.product.fields.name *"` 

to append `*` to a normal label?

**Comment by jpetitcolas** [comment]
I would instead check the `validate` prop and add the `*` if the field is required. But +1 for the feature.

**Comment by fzaninotto** [comment]
True, this is in the Material Design guidelines

https://material.io/guidelines/components/text-fields.html#text-fields-layout

![image](https://cloud.githubusercontent.com/assets/99944/26550301/56371436-447d-11e7-872c-928950f79ae6.png)

However, since the `required` property is only a function, we'll have to compare function identity.
