### ISSUE TITLE
Add support for ReferenceManyInput field

### ISSUE THREAD

**Issue by rtnpro** [marmelab/admin-on-rest#725]
``ReferenceManyField`` is quite useful in displaying ManyToMany and OneToMany relations in ``Edit`` page of a resource. It's be really good to allow editing and adding these ManyToMany relations from the ``Edit`` page, similar to Django's admin's ``GenericTabularInline``.

I have created this pull request: https://github.com/marmelab/admin-on-rest/pull/724 to discuss and seek help in implementing the above said feature. Please help me adding support for this feature.

**Comment by fzaninotto** [comment]
[Version 1.1](https://github.com/marmelab/admin-on-rest/releases/tag/v1.1.0) introduces `<ReferenceArrayInput>`, which is as far as we'll get in admin-on-rest core. For many-to-many relationships based on foreign keys, you'll have to do that in userland. Feel free to create a standalone extension and publish it, we'll link to it in the documentation

**Comment by danilobuerger** [comment]
@fzaninotto So if someone would submit a working PR for `ReferenceManyInput` you wouldn't accept it?

**Comment by fzaninotto** [comment]
If someone finds a smart way of making it generic without too much hassle, I'd consider it, without guarantee of merge. But if you're into such a feature, fell free to publish it as a standalone package first. If it's good and if you still want to contribute it to the core, we'll take it. Otherwise, developers cans still use it from your package !
