### ISSUE TITLE
Relating to responsive design

### ISSUE THREAD

**Issue by kakoli4109** [marmelab/admin-on-rest#726]
Is there possibility to make admin-on-rest Responsive? All the components are not functional below 
1024 X 768.

**Comment by fzaninotto** [comment]
Please be more specific about which components are problematic for you. As you can see on the demo, if you resize the window to a mobile device shape, it continues to work. Besides, admin-on-rest provides a [responsive component](https://marmelab.com/admin-on-rest/Theming.html#responsive-utility).

**Comment by jakubknejzlik** [comment]
When I try demo page I can see some layout issues. Also same thing happens when I resize desktop browser window to smaller size.
![img_1304](https://user-images.githubusercontent.com/1138023/29766292-8ce39dda-8bde-11e7-9582-3fd4582caf17.PNG)
![img_1305](https://user-images.githubusercontent.com/1138023/29766291-8ce37cba-8bde-11e7-8a93-389c7450263d.PNG)
![img_1307](https://user-images.githubusercontent.com/1138023/29766379-dacf4d28-8bde-11e7-8741-e75f51fb3e57.PNG)

Also when page with large table is displayed, there's no way I can move the table to see all columns:
![img_1306](https://user-images.githubusercontent.com/1138023/29766290-8ce2a6e6-8bde-11e7-9ba9-f287139a24f3.PNG)

**Comment by djhi** [comment]
Yes, we did not optimize the demo for mobile usage. This demo needs some love.
