### ISSUE TITLE
More on File uploads => Multipart

### ISSUE THREAD

**Issue by ceddyb** [marmelab/admin-on-rest#767]
Am in a situation where i'd like all files uploaded to be sent as multi-part, there are forms where i have many file inputs but i can't figure out a way to loop through all the file fields without repeating my code for each and every file input field.

To my observation, admin-on-rest is ideal for text-content only. I mean managing content that doesn't need file uploads e.t.c

Due to the fact that your library lacks in-depth documentation on files handling, for example i only found ImageInput for handling image files, what about other types of files?  these are critical aspects of a modern admin-dashboard.

Regards i do appreciate this lib, Awesome lib man!

**Comment by fzaninotto** [comment]
Admin-on-rest lacks documentation on submitting multipart data with AJAX because it's not in its scope. Admin-on-rest provides a resource created or edited via a web interface as à JSON object, it's your job to pass it to your backend. The reason is that since REST isn't standardized, there is no way we can adapt to your own API with a library. 

Google for "Multipart AJAX" to find answers to your question.
