### ISSUE TITLE
Add prefix to Router

### ISSUE THREAD

**Issue by fab1an** [marmelab/admin-on-rest#858]
Hi, we use a little hash-based routing system, which isn't redux-router.

1. I make my own router '#/Admin' so the interface opens
2. Then I just stop processing routes to not interface with admin-on-rest's router, which seems to work.

The problem is only that I get routes like `#/pages` in the url-bar, which, when I reload the page don't work (because our router is in charge again).
Is there a way to forward an url to rest-on-admin? Make it so the url will be named `#/Admin/pages`?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
