### ISSUE TITLE
Error after save in editing, bad pagination

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#867]
Hi, when you save an item in the EDIT section, and you press SAVE, the URL is not matching with the current pagination. Example:

In the first screenshot all is fine, the page param is correct (36), and the curren page showing the data is correct too:

![screen shot 2017-07-17 at 11 45 01](https://user-images.githubusercontent.com/1420409/28263022-9beba404-6ae5-11e7-8ec4-0bd4b4a9a6ac.png)

After press in edit any element in the list you go to the form edit, and you press SAVE:
![screen shot 2017-07-17 at 11 43 48](https://user-images.githubusercontent.com/1420409/28263092-d724e0e4-6ae5-11e7-8b38-a4efdd2010fa.png)

And this is the error, you are currently in the page 36, but the URL is bad:

![screen shot 2017-07-17 at 11 43 59](https://user-images.githubusercontent.com/1420409/28263073-c6e7ef32-6ae5-11e7-8308-f1402cd9b912.png)

I think is better go to the show view, and view the changes... but this is a suggestion :)

Thanks.

**Comment by chemitaxis** [comment]
This error happens if you go from VIEW to LIST too. Thanks.

**Comment by fzaninotto** [comment]
It's not a bug... it's a feature!

You may notice that the list params are saved in the session. E.g try to add a filter or a sort to a list, then go to a show view, then go back to the list by clicking on the resource name in the left sidebar. You'll find the list in exactly the same state as it was the last time you saw it (filtered and sorted), even if the url doesn't show it.

That's a choice we made to store the single source of truth in the Redux store rather than in the URL for the list params. That leads to urls sometimes looking out of sync with the content, but that's not a bug.
