### ISSUE TITLE
Add an extra text input to file input

### ISSUE THREAD

**Issue by norx85** [marmelab/admin-on-rest#902]
I think it would be useful to have the possibility to add an extra text input to all entry in a multiple ImageInput (or FileInput).
I tried to write a custom ImageField by myself with a extra text input but i don't know how to pass these extra values to the form data to send on the server.

This is the code of the custom ImageField i wrote (not working), maybe would be useful:

```
import React from 'react';
import PropTypes from 'prop-types';
import get from 'lodash.get';
import TextField from 'material-ui/TextField';
import {FieldTitle} from "admin-on-rest";
const styles = {
    image: {
        margin: '5px',
        height: '100px',
        width: '100px',
        objectFit : 'cover',
        clear: 'both'
    },
    textInputWrap: {
        display : 'flex',
        flexDirection: 'column',
        alignSelf : 'center',
        margin: '10px'
    },
    textInputLabel: {
        color: 'rgba(0, 0, 0, 0.3)',
        alignSelf : 'flex-start'
    },
    textInput: {
        alignSelf : 'flex-end'
    }
};

export const ImageImportField = ({ elStyle = {}, record, source, src, title }) => {
    const sourceValue = get(record, source);
    if (!sourceValue) {
        return <div />;
    }
    const titleValue = get(record, title) || title;
    const fileHeader = record.rawFile;
    return (
        <div style={elStyle}>
            <img
                title={titleValue}
                alt={titleValue}
                src={sourceValue}
                style={styles.image}
            />
            <div  style={styles.textInputWrap} >
                <span style={styles.textInputLabel}>{fileHeader.name}</span>
                <TextField
                    type="text"
                    name="filename"
                    defaultValue={fileHeader.name}
                    floatingLabelText={<FieldTitle label="Filename" />}
                    style={styles.textInput}
                />
            </div>
        </div>
    );
};

ImageImportField.propTypes = {
    elStyle: PropTypes.object,
    record: PropTypes.object,
    source: PropTypes.string.isRequired,
    nameSource: PropTypes.string.isRequired,
    title: PropTypes.string,
};

export default ImageImportField;
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by norx85** [comment]
Hi, I'm not asking for a "how to", i'm asking for a new feature if possible. For now it's impossible to achive this scenario, so i think it's useless to ask for that on stackoverflow.

**Comment by djhi** [comment]
It's possible, you need to write a custom input. See the [documentation](https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component)
