### ISSUE TITLE
How to access a json field with dot in name?

### ISSUE THREAD

**Issue by datafibers** [marmelab/admin-on-rest#904]
I have a sample json to show as follows
how I can display a field "connector.class"?
If I use <TextField source="connector.class" label="ConnectorConfig.Class" />, it will show nothing since it interpreted as next json.

{
    "connector.class" : "com.datafibers.kafka.connect.FileGenericSourceConnector",
    "schema.registry.uri" : "http://localhost:8081",
    "cuid" : "597bd1dc7985373920904f81",
    "file.location" : "/home/vagrant/df_data/",
    "tasks.max" : "1",
    "file.glob" : "*.{json,csv}",
    "file.overwrite" : "true",
    "schema.subject" : "test_value",
    "topic" : "stock"
  }

**Comment by kodepareek** [comment]
This is a question for StackOverFlow not github. Please ask this there.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
