### ISSUE TITLE
How to build a saved custom field

### ISSUE THREAD

**Issue by lauyaun** [marmelab/admin-on-rest#910]
For example, a product table has 2 fields, id, product_name. The merchandise has a child table that holds the sku collection of the item. Now I need to add or edit the time, select multiple sku, resulting in a combination of data. But in the create and edit forms, I can not customize a field to save the collection. Admin-on-rest Is there any other way to support custom field data submission and editing? Thank you！

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by lauyaun** [comment]
i see ,thank you

**Comment by afilp** [comment]
@fzaninotto Thanks, we see that these questions are rarely answered in Stack Overflow though. Nobody (except your team) has really good answers on HOW-TO questions and you are rightfully very busy in developing. There are many times that we do not know how to do things, since the concepts used in the package are quite advanced and we need to figure out where to look for. 

Thanks again for your great effort, I just mention the above just to show that it is difficult for us (that do not know all the internals) to follow without getting answers to those questions.

**Comment by fzaninotto** [comment]
I understand your pain, but we just can't cope with support requests *and* the development of the core at the same time. If your bug is blocking, I suggest you add a bounty in stackOverflow.

**Comment by afilp** [comment]
@fzaninotto Thanks for the answer. A dedicated "support" dev that just answers all questions would be great but I understand that this needs payment and most likely this is not feasible from a "not-for-profit" effort which is not backed by a company.  More answered questions would expand the developer's audience though and it would be good for all of us. Thanks again!
