### ISSUE TITLE
React is listed as a dependency, not a peerDependency

### ISSUE THREAD

**Issue by vcarl** [marmelab/admin-on-rest#932]
We're looking to embed this in an existing app, but are blocked because we're ended up with multiple copies of React loaded. That's causing a number of obscure problems, most notably that the initial request for data isn't being sent out. I forked the repo to verify that moving React/ReactDOM to peerDependencies resolved the issue, which it does.

I considered opening a PR, but I wanted to discuss it first. It's a small technical change but I realize it has an outsized impact on documentation and getting the project up and running on its own.

**Comment by jpetitcolas** [comment]
I would be +1 for this change. 

Not sure about the impact? It seems quite limited to me. We just need to `yarn install react` in addition to `admin-on-rest`, and add it to the `dependencies` of the demo. And it may even fix some issues we have (had?) with `npm link`.

Yet, as it would be a BC break, it would need a new version. Perhaps for the 2.0?

**Comment by fzaninotto** [comment]
The problem is that admin-on-rest currently doesn't support the latest React version (see #802), so to have it work with another codebase, your codebase must specify exactly the same React version as admin-on-rest. In this case, being a dependency or a peerDependency doesn't matter.

Also, as @jpetitcolas said, this is a breaking change. We'll keep it in mind, but until we plan a major release, this is a no go.

**Comment by vcarl** [comment]
I installed the exact version admin-on-rest was using and continued to get the warning about multiple copies of React being loaded. I'm not sure why npm wasn't able to dedupe it (which is what I was expecting), but I have not been able to resolve this without forking to add React as a peerDep

**Comment by fzaninotto** [comment]
Maybe you have a `.lock` file? If so, remove it. Clearing the npm cache may help, too.
