### ISSUE TITLE
Independence Submit button for Tabbed Form in Create

### ISSUE THREAD

**Issue by congaductq** [marmelab/admin-on-rest#957]
Hi,

I already made 2 types of create page:
1. Create single record.
![screen shot 2017-08-22 at 4 31 26 pm](https://user-images.githubusercontent.com/19276305/29556148-823e44ec-8757-11e7-82bd-c008d227e26b.png)

2. Import multiple records from xlsx file.
![screen shot 2017-08-22 at 4 31 28 pm](https://user-images.githubusercontent.com/19276305/29556152-86035eaa-8757-11e7-9301-427ad71fcd18.png)

Now I want to implement 2 buttons: Save (1) and Import (2) independently. It's mean when I click on button (1), only button (1) works.

Thank you guys.

Sorry, my English is not good.

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
