### ISSUE TITLE
Always show specific filter in list view

### ISSUE THREAD

**Issue by raythree** [marmelab/admin-on-rest#965]
Is there a way to always show a specific filter (or filters) in the list view, e.g. not requiring the user to Add Filter and always displaying it without the "remove filter" button?

Thanks

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
